// Native fixture generator for the OpenEXR-wasm coverage matrix. Builds small
// (<200 KB) committed EXRs exercising every decode path plus a large PIZ for
// the decode benchmark. Provenance: synthetically generated by this file
// against OpenEXR v3.4.9 / Imath v3.2.2. Built + run by build-native.sh.
//
//   gen <outdir>
//
// Produces: rgb-zip-half-64x48.exr, rgb-piz-float-64x48.exr,
//           luma-chroma-64x48.exr, deep-32x32.exr, htj2k-64x48.exr,
//           tiled-zip-half-64x48.exr, and (large, uncommitted)
//           rgb-piz-half-1024x1024.exr for benchmarking.

#include <cmath>
#include <string>
#include <vector>

#include <ImfOutputFile.h>
#include <ImfTiledOutputFile.h>
#include <ImfRgbaFile.h>
#include <ImfDeepScanLineOutputFile.h>
#include <ImfMultiPartOutputFile.h>
#include <ImfOutputPart.h>
#include <ImfChannelList.h>
#include <ImfFrameBuffer.h>
#include <ImfDeepFrameBuffer.h>
#include <ImfHeader.h>
#include <ImfArray.h>
#include <ImfPartType.h>
#include <half.h>

using namespace Imf;
using namespace Imath;

static float wave(int x, int y, int c) {
  return 0.5f + 0.5f * std::sin((x * 0.21f + y * 0.13f) + c * 2.1f);
}

// Flat RGB half, chosen compression.
static void writeFlatHalf(const std::string& path, int w, int h, Compression comp) {
  Array2D<half> R(h, w), G(h, w), B(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      R[y][x] = wave(x, y, 0);
      G[y][x] = wave(x, y, 1);
      B[y][x] = wave(x, y, 2);
    }
  Header hd(w, h);
  hd.compression() = comp;
  hd.channels().insert("R", Channel(HALF));
  hd.channels().insert("G", Channel(HALF));
  hd.channels().insert("B", Channel(HALF));
  OutputFile file(path.c_str(), hd);
  FrameBuffer fb;
  fb.insert("R", Slice(HALF, (char*)&R[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("G", Slice(HALF, (char*)&G[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("B", Slice(HALF, (char*)&B[0][0], sizeof(half), sizeof(half) * w));
  file.setFrameBuffer(fb);
  file.writePixels(h);
}

// Flat RGB float, chosen compression (exercises the f32 output path).
static void writeFlatFloat(const std::string& path, int w, int h, Compression comp) {
  Array2D<float> R(h, w), G(h, w), B(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      R[y][x] = wave(x, y, 0);
      G[y][x] = wave(x, y, 1);
      B[y][x] = wave(x, y, 2);
    }
  Header hd(w, h);
  hd.compression() = comp;
  hd.channels().insert("R", Channel(FLOAT));
  hd.channels().insert("G", Channel(FLOAT));
  hd.channels().insert("B", Channel(FLOAT));
  OutputFile file(path.c_str(), hd);
  FrameBuffer fb;
  fb.insert("R", Slice(FLOAT, (char*)&R[0][0], sizeof(float), sizeof(float) * w));
  fb.insert("G", Slice(FLOAT, (char*)&G[0][0], sizeof(float), sizeof(float) * w));
  fb.insert("B", Slice(FLOAT, (char*)&B[0][0], sizeof(float), sizeof(float) * w));
  file.setFrameBuffer(fb);
  file.writePixels(h);
}

// Luminance-chroma: RgbaOutputFile with WRITE_YC stores Y/RY/BY subsampled.
static void writeLumaChroma(const std::string& path, int w, int h) {
  Array2D<Rgba> px(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x)
      px[y][x] = Rgba(wave(x, y, 0), wave(x, y, 1), wave(x, y, 2), 1.0f);
  RgbaOutputFile file(path.c_str(), w, h, WRITE_YC);
  file.setFrameBuffer(&px[0][0], 1, w);
  file.writePixels(h);
}

// Tiled ZIP half (exercises the flat-tiled read path).
static void writeTiledHalf(const std::string& path, int w, int h) {
  Array2D<half> R(h, w), G(h, w), B(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      R[y][x] = wave(x, y, 0);
      G[y][x] = wave(x, y, 1);
      B[y][x] = wave(x, y, 2);
    }
  Header hd(w, h);
  hd.compression() = ZIP_COMPRESSION;
  hd.channels().insert("R", Channel(HALF));
  hd.channels().insert("G", Channel(HALF));
  hd.channels().insert("B", Channel(HALF));
  hd.setTileDescription(TileDescription(16, 16, ONE_LEVEL));
  TiledOutputFile file(path.c_str(), hd);
  FrameBuffer fb;
  fb.insert("R", Slice(HALF, (char*)&R[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("G", Slice(HALF, (char*)&G[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("B", Slice(HALF, (char*)&B[0][0], sizeof(half), sizeof(half) * w));
  file.setFrameBuffer(fb);
  file.writeTiles(0, file.numXTiles() - 1, 0, file.numYTiles() - 1);
}

// HTJ2K compression (OpenEXR 3.4 + OpenJPH) — the whole point of the pivot.
static void writeHtj2k(const std::string& path, int w, int h) {
  Array2D<half> R(h, w), G(h, w), B(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      R[y][x] = wave(x, y, 0);
      G[y][x] = wave(x, y, 1);
      B[y][x] = wave(x, y, 2);
    }
  Header hd(w, h);
  hd.compression() = HTJ2K32_COMPRESSION;
  hd.channels().insert("R", Channel(HALF));
  hd.channels().insert("G", Channel(HALF));
  hd.channels().insert("B", Channel(HALF));
  OutputFile file(path.c_str(), hd);
  FrameBuffer fb;
  fb.insert("R", Slice(HALF, (char*)&R[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("G", Slice(HALF, (char*)&G[0][0], sizeof(half), sizeof(half) * w));
  fb.insert("B", Slice(HALF, (char*)&B[0][0], sizeof(half), sizeof(half) * w));
  file.setFrameBuffer(fb);
  file.writePixels(h);
}

// Deep scanline: 1-2 premultiplied RGBA samples per pixel at varying Z.
static void writeDeep(const std::string& path, int w, int h) {
  Header hd(w, h);
  hd.setType(DEEPSCANLINE);
  hd.compression() = ZIPS_COMPRESSION;
  hd.channels().insert("R", Channel(FLOAT));
  hd.channels().insert("G", Channel(FLOAT));
  hd.channels().insert("B", Channel(FLOAT));
  hd.channels().insert("A", Channel(FLOAT));
  hd.channels().insert("Z", Channel(FLOAT));

  Array2D<unsigned int> counts(h, w);
  Array2D<float*> Rp(h, w), Gp(h, w), Bp(h, w), Ap(h, w), Zp(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      unsigned int n = ((x + y) % 3 == 0) ? 2u : 1u;
      counts[y][x] = n;
      Rp[y][x] = new float[n]; Gp[y][x] = new float[n]; Bp[y][x] = new float[n];
      Ap[y][x] = new float[n]; Zp[y][x] = new float[n];
      // Back sample (larger Z) written FIRST (s0, Z=10) to prove the decoder
      // sorts by Z, not file order. The FRONT sample (s1, Z=1) is semi-transparent
      // (a=0.5) and the BACK is opaque (a=1) so the back DOES contribute to a full
      // composite — making the depth-slider test meaningful: clipping between the
      // two (e.g. zClip=7) drops the back and yields ONLY the front (a=0.5), which
      // DIFFERS from the full flatten (a=1). Single-sample pixels sit at Z=5.
      for (unsigned int s = 0; s < n; ++s) {
        float a = (n == 2 && s == 1) ? 0.5f : 1.0f;  // front sample (s1, Z=1) semi-transparent
        Rp[y][x][s] = a * wave(x, y, s);
        Gp[y][x][s] = a * wave(x, y, s + 1);
        Bp[y][x][s] = a * wave(x, y, s + 2);
        Ap[y][x][s] = a;
        Zp[y][x][s] = (n == 2) ? (s == 0 ? 10.0f : 1.0f) : 5.0f;  // s0 is BEHIND s1
      }
    }

  DeepScanLineOutputFile file(path.c_str(), hd);
  DeepFrameBuffer fb;
  fb.insertSampleCountSlice(Slice(UINT, (char*)&counts[0][0], sizeof(unsigned int),
                                  sizeof(unsigned int) * w));
  auto add = [&](const char* n, Array2D<float*>& p) {
    fb.insert(n, DeepSlice(FLOAT, (char*)&p[0][0], sizeof(float*),
                           sizeof(float*) * w, sizeof(float)));
  };
  add("R", Rp); add("G", Gp); add("B", Bp); add("A", Ap); add("Z", Zp);
  file.setFrameBuffer(fb);
  file.writePixels(h);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      delete[] Rp[y][x]; delete[] Gp[y][x]; delete[] Bp[y][x];
      delete[] Ap[y][x]; delete[] Zp[y][x];
    }
}

// Deep scanline with EMPTY pixels (holes) — for the region-select z-range test's
// count=0 (empty region) path. Left half (x<4) has one sample at Z=3; right half
// (x>=4) has ZERO samples (a genuine hole).
static void writeDeepHoles(const std::string& path, int w, int h) {
  Header hd(w, h);
  hd.setType(DEEPSCANLINE);
  hd.compression() = ZIPS_COMPRESSION;
  hd.channels().insert("R", Channel(FLOAT));
  hd.channels().insert("G", Channel(FLOAT));
  hd.channels().insert("B", Channel(FLOAT));
  hd.channels().insert("A", Channel(FLOAT));
  hd.channels().insert("Z", Channel(FLOAT));

  Array2D<unsigned int> counts(h, w);
  Array2D<float*> Rp(h, w), Gp(h, w), Bp(h, w), Ap(h, w), Zp(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      unsigned int n = (x < w / 2) ? 1u : 0u;  // right half is empty
      counts[y][x] = n;
      Rp[y][x] = n ? new float[n] : nullptr;
      Gp[y][x] = n ? new float[n] : nullptr;
      Bp[y][x] = n ? new float[n] : nullptr;
      Ap[y][x] = n ? new float[n] : nullptr;
      Zp[y][x] = n ? new float[n] : nullptr;
      if (n) {
        Rp[y][x][0] = wave(x, y, 0); Gp[y][x][0] = wave(x, y, 1);
        Bp[y][x][0] = wave(x, y, 2); Ap[y][x][0] = 1.0f; Zp[y][x][0] = 3.0f;
      }
    }
  DeepScanLineOutputFile file(path.c_str(), hd);
  DeepFrameBuffer fb;
  fb.insertSampleCountSlice(Slice(UINT, (char*)&counts[0][0], sizeof(unsigned int),
                                  sizeof(unsigned int) * w));
  auto add = [&](const char* n, Array2D<float*>& p) {
    fb.insert(n, DeepSlice(FLOAT, (char*)&p[0][0], sizeof(float*),
                           sizeof(float*) * w, sizeof(float)));
  };
  add("R", Rp); add("G", Gp); add("B", Bp); add("A", Ap); add("Z", Zp);
  file.setFrameBuffer(fb);
  file.writePixels(h);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      delete[] Rp[y][x]; delete[] Gp[y][x]; delete[] Bp[y][x];
      delete[] Ap[y][x]; delete[] Zp[y][x];
    }
}

// Large DENSE deep scanline (uncommitted) for the retained-vs-redecode
// benchmark — Trunks-scale foliage density: a variable 1..K samples/pixel so
// the retained CSR far exceeds the flat image (the case that must fall back to
// cache-bytes + redecode). Front-to-back varying Z; premultiplied.
static void writeDeepDense(const std::string& path, int w, int h, int maxSamples) {
  Header hd(w, h);
  hd.setType(DEEPSCANLINE);
  hd.compression() = ZIPS_COMPRESSION;
  hd.channels().insert("R", Channel(FLOAT));
  hd.channels().insert("G", Channel(FLOAT));
  hd.channels().insert("B", Channel(FLOAT));
  hd.channels().insert("A", Channel(FLOAT));
  hd.channels().insert("Z", Channel(FLOAT));

  Array2D<unsigned int> counts(h, w);
  Array2D<float*> Rp(h, w), Gp(h, w), Bp(h, w), Ap(h, w), Zp(h, w);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      unsigned int n = 1u + (unsigned int)((x * 7 + y * 13) % maxSamples);
      counts[y][x] = n;
      Rp[y][x] = new float[n]; Gp[y][x] = new float[n]; Bp[y][x] = new float[n];
      Ap[y][x] = new float[n]; Zp[y][x] = new float[n];
      for (unsigned int s = 0; s < n; ++s) {
        float a = 0.3f;  // semi-transparent so many samples contribute
        Rp[y][x][s] = a * wave(x, y, s);
        Gp[y][x][s] = a * wave(x, y, s + 1);
        Bp[y][x][s] = a * wave(x, y, s + 2);
        Ap[y][x][s] = a;
        Zp[y][x][s] = 1.0f + 2.0f * (float)s;  // ascending Z per sample
      }
    }
  DeepScanLineOutputFile file(path.c_str(), hd);
  DeepFrameBuffer fb;
  fb.insertSampleCountSlice(Slice(UINT, (char*)&counts[0][0], sizeof(unsigned int),
                                  sizeof(unsigned int) * w));
  auto add = [&](const char* n, Array2D<float*>& p) {
    fb.insert(n, DeepSlice(FLOAT, (char*)&p[0][0], sizeof(float*),
                           sizeof(float*) * w, sizeof(float)));
  };
  add("R", Rp); add("G", Gp); add("B", Bp); add("A", Ap); add("Z", Zp);
  file.setFrameBuffer(fb);
  file.writePixels(h);
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      delete[] Rp[y][x]; delete[] Gp[y][x]; delete[] Bp[y][x];
      delete[] Ap[y][x]; delete[] Zp[y][x];
    }
}


// Layered AOV file (single part): default RGBA + diffuse.RGB + specular.RGB +
// a bare Z — the channel-GROUPING coverage fixture. Every channel is a CONSTANT
// value ((index+1)/16) so selector tests can assert exact planes:
//   R=1/16 G=2/16 B=3/16 A=4/16 · diffuse.R=5/16 .G=6/16 .B=7/16 ·
//   specular.R=8/16 .G=9/16 .B=10/16 · Z=11/16
static void writeLayeredAov(const std::string& path, int w, int h) {
  const char* names[] = {"R", "G", "B", "A",
                         "diffuse.R", "diffuse.G", "diffuse.B",
                         "specular.R", "specular.G", "specular.B", "Z"};
  const int n = sizeof(names) / sizeof(names[0]);
  Header hd(w, h);
  hd.compression() = ZIP_COMPRESSION;
  for (int i = 0; i < n; ++i) hd.channels().insert(names[i], Channel(HALF));
  std::vector<std::vector<half>> bufs(n, std::vector<half>(size_t(w) * h));
  FrameBuffer fb;
  for (int i = 0; i < n; ++i) {
    const half v = half(float(i + 1) / 16.0f);
    for (auto& px : bufs[i]) px = v;
    fb.insert(names[i], Slice(HALF, (char*)bufs[i].data(), sizeof(half), sizeof(half) * w));
  }
  OutputFile file(path.c_str(), hd);
  file.setFrameBuffer(fb);
  file.writePixels(h);
}

// Multi-part scanline file: part 0 "beauty" (RGB half, constants .1/.2/.3) and
// part 1 "aux" (Z float const 7.5 + mask half const 1.0) — the PART-selection
// coverage fixture (part by index AND by name; scalar channels in a part).
static void writeMultiPart2(const std::string& path, int w, int h) {
  std::vector<Header> headers;
  {
    Header hd(w, h);
    hd.setName("beauty");
    hd.setType(SCANLINEIMAGE);
    hd.compression() = ZIP_COMPRESSION;
    hd.channels().insert("R", Channel(HALF));
    hd.channels().insert("G", Channel(HALF));
    hd.channels().insert("B", Channel(HALF));
    headers.push_back(hd);
  }
  {
    Header hd(w, h);
    hd.setName("aux");
    hd.setType(SCANLINEIMAGE);
    hd.compression() = ZIP_COMPRESSION;
    hd.channels().insert("Z", Channel(FLOAT));
    hd.channels().insert("mask", Channel(HALF));
    headers.push_back(hd);
  }
  MultiPartOutputFile file(path.c_str(), headers.data(), (int)headers.size());
  {
    std::vector<half> R(size_t(w) * h, half(0.1f)), G(size_t(w) * h, half(0.2f)),
        B(size_t(w) * h, half(0.3f));
    FrameBuffer fb;
    fb.insert("R", Slice(HALF, (char*)R.data(), sizeof(half), sizeof(half) * w));
    fb.insert("G", Slice(HALF, (char*)G.data(), sizeof(half), sizeof(half) * w));
    fb.insert("B", Slice(HALF, (char*)B.data(), sizeof(half), sizeof(half) * w));
    OutputPart part(file, 0);
    part.setFrameBuffer(fb);
    part.writePixels(h);
  }
  {
    std::vector<float> Z(size_t(w) * h, 7.5f);
    std::vector<half> M(size_t(w) * h, half(1.0f));
    FrameBuffer fb;
    fb.insert("Z", Slice(FLOAT, (char*)Z.data(), sizeof(float), sizeof(float) * w));
    fb.insert("mask", Slice(HALF, (char*)M.data(), sizeof(half), sizeof(half) * w));
    OutputPart part(file, 1);
    part.setFrameBuffer(fb);
    part.writePixels(h);
  }
}


// Visually rich layered AOV DEMO file (gallery + docs): a plausible "render"
// with beauty RGBA + diffuse/specular layers + signed normals + a radial Z.
// Content is deterministic waves — no assets. 128x96 HALF, ZIP.
static void writeLayeredDemo(const std::string& path, int w, int h) {
  const char* names[] = {"R", "G", "B", "A",
                         "diffuse.R", "diffuse.G", "diffuse.B",
                         "specular.R", "specular.G", "specular.B",
                         "normal.X", "normal.Y", "normal.Z", "Z"};
  const int n = sizeof(names) / sizeof(names[0]);
  Header hd(w, h);
  hd.compression() = ZIP_COMPRESSION;
  for (int i = 0; i < n; ++i) hd.channels().insert(names[i], Channel(HALF));
  std::vector<std::vector<half>> bufs(n, std::vector<half>(size_t(w) * h));
  for (int y = 0; y < h; ++y)
    for (int x = 0; x < w; ++x) {
      const size_t i = size_t(y) * w + x;
      const float u = float(x) / w, v = float(y) / h;
      // Diffuse: soft colored waves.
      const float dr = 0.30f + 0.25f * wave(x, y, 0);
      const float dg = 0.25f + 0.25f * wave(x, y, 1);
      const float db = 0.35f + 0.25f * wave(x, y, 2);
      // Specular: sharp moving highlights (wave^8) with a warm tint.
      const float s = std::pow(wave(x * 2, y * 2, 1), 8.0f);
      const float sr = 1.2f * s, sg = 1.0f * s, sb = 0.7f * s;
      // Normals: a smooth signed field (a bumpy plane facing +Z).
      const float nx = 0.6f * std::sin(u * 9.0f), ny = 0.6f * std::sin(v * 7.0f);
      const float nz = std::sqrt(std::max(0.0f, 1.0f - nx * nx - ny * ny));
      // Z: radial depth from centre, 1..6.
      const float dx = u - 0.5f, dy = v - 0.5f;
      const float z = 1.0f + 5.0f * std::sqrt(dx * dx + dy * dy) * 1.6f;
      const float vals[] = {dr + sr, dg + sg, db + sb, 1.0f,
                            dr, dg, db, sr, sg, sb, nx, ny, nz, z};
      for (int c = 0; c < n; ++c) bufs[c][i] = half(vals[c]);
    }
  FrameBuffer fb;
  for (int c = 0; c < n; ++c)
    fb.insert(names[c], Slice(HALF, (char*)bufs[c].data(), sizeof(half), sizeof(half) * w));
  OutputFile file(path.c_str(), hd);
  file.setFrameBuffer(fb);
  file.writePixels(h);
}

int main(int argc, char** argv) {
  std::string dir = (argc > 1) ? argv[1] : ".";
  auto p = [&](const char* n) { return dir + "/" + n; };
  writeFlatHalf(p("rgb-zip-half-64x48.exr"), 64, 48, ZIP_COMPRESSION);
  writeFlatFloat(p("rgb-piz-float-64x48.exr"), 64, 48, PIZ_COMPRESSION);
  writeLumaChroma(p("luma-chroma-64x48.exr"), 64, 48);
  writeTiledHalf(p("tiled-zip-half-64x48.exr"), 64, 48);
  writeHtj2k(p("htj2k-half-64x48.exr"), 64, 48);
  writeDeep(p("deep-rgba-32x32.exr"), 32, 32);
  writeDeepHoles(p("deep-holes-8x8.exr"), 8, 8);
  writeLayeredAov(p("layers-aov-64x48.exr"), 64, 48);
  writeMultiPart2(p("multipart-2part-64x48.exr"), 64, 48);
  writeLayeredDemo(p("layers-demo-128x96.exr"), 128, 96);
  writeFlatHalf(p("rgb-piz-half-1024x1024.exr"), 1024, 1024, PIZ_COMPRESSION);
  // Trunks-scale dense deep for the retained-vs-redecode benchmark (uncommitted).
  writeDeepDense(p("deep-dense-512x512.exr"), 512, 512, 12);
  return 0;
}
