#!/usr/bin/env python3
"""Generate the committed SSIM fixtures (`ssim.json`) from scikit-image.

This is the provenance for the SSIM CPU-reference node test
(`ssim-reference.test.ts`). It builds a handful of deterministic sRGB image
pairs, converts each to the SAME linear Rec.709 luminance plane the TS
reference / GPU kernel compute, then runs scikit-image's
`structural_similarity` on those luminance planes and records the per-pixel
SSIM map + the interior-crop mean (`mssim`).

Exact skimage params (must match `ssim-reference.ts`):
    structural_similarity(
        lumRef, lumTest,
        gaussian_weights=True,   # true Gaussian window (not a box)
        sigma=1.5,               # 11-tap (radius = int(3.5*1.5+0.5) = 5)
        use_sample_covariance=False,  # cov_norm = 1
        data_range=1.0,          # L = 1 (luminance is [0,1])
        full=True,               # return the per-pixel map
    )
(K1=0.01, K2=0.03 are skimage defaults, matching Wang et al. 2004.)

Run (from the repo root):
    uv run --with scikit-image --with numpy \\
        ui/src/lib/cairn-plot/engine/kernels/__fixtures__/gen_ssim_fixtures.py
"""
from __future__ import annotations

import json
import os

import numpy as np
from skimage.metrics import structural_similarity


def srgb2linear(c: np.ndarray) -> np.ndarray:
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def luminance(rgb: np.ndarray) -> np.ndarray:
    """sRGB [0,1] HxWx3 -> linear Rec.709 luminance HxW, clamped to [0,1]."""
    lin = srgb2linear(rgb)
    y = 0.2126 * lin[..., 0] + 0.7152 * lin[..., 1] + 0.0722 * lin[..., 2]
    return np.clip(y, 0.0, 1.0)


def make_pair(w: int, h: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Deterministic sRGB pair (float32, [0,1]), HxWx3 — mirrors the TS harness."""
    rng = np.random.default_rng(seed)
    ref = rng.random((h, w, 3), dtype=np.float64)
    test = np.clip(ref + (rng.random((h, w, 3)) - 0.5) * 0.25, 0.0, 1.0)
    return ref.astype(np.float32), test.astype(np.float32)


def gradient_pair(w: int, h: int) -> tuple[np.ndarray, np.ndarray]:
    xs = np.linspace(0, 1, w)
    ys = np.linspace(0, 1, h)
    gx, gy = np.meshgrid(xs, ys)
    ref = np.stack([gx, gy, np.full_like(gx, 0.5)], axis=-1)
    test = np.stack([gx[:, ::-1], gy, np.full_like(gx, 0.5)], axis=-1)  # x-flipped
    return ref.astype(np.float32), test.astype(np.float32)


def solid_pair(w: int, h: int) -> tuple[np.ndarray, np.ndarray]:
    ref = np.tile(np.array([0.8, 0.2, 0.2], np.float32), (h, w, 1))
    test = np.tile(np.array([0.2, 0.2, 0.8], np.float32), (h, w, 1))
    return ref, test


def case(name: str, ref: np.ndarray, test: np.ndarray) -> dict:
    h, w = ref.shape[:2]
    lum_ref = luminance(ref).astype(np.float64)
    lum_test = luminance(test).astype(np.float64)
    mssim, full = structural_similarity(
        lum_ref,
        lum_test,
        gaussian_weights=True,
        sigma=1.5,
        use_sample_covariance=False,
        data_range=1.0,
        full=True,
    )
    return {
        "name": name,
        "width": int(w),
        "height": int(h),
        "refSRGB": [float(v) for v in ref.reshape(-1)],
        "testSRGB": [float(v) for v in test.reshape(-1)],
        "expectedSsim": [float(v) for v in np.asarray(full).reshape(-1)],
        "expectedMssim": float(mssim),
    }


def main() -> None:
    import skimage

    cases = [
        case("solid_red_vs_blue", *solid_pair(16, 16)),
        case("gradient_flipped", *gradient_pair(16, 16)),
        case("noise_perturbed", *make_pair(20, 18, 7)),
        case("noise_perturbed_2", *make_pair(24, 24, 42)),
    ]
    out = {
        "provenance": (
            f"scikit-image=={skimage.__version__} structural_similarity on linear "
            "Rec.709 luminance planes (sRGB->linear->Y, clamped [0,1]); params: "
            "gaussian_weights=True, sigma=1.5, use_sample_covariance=False, "
            "data_range=1, K1=0.01, K2=0.03 (defaults). Generated by "
            "gen_ssim_fixtures.py (beside this file)."
        ),
        "sigma": 1.5,
        "K1": 0.01,
        "K2": 0.03,
        "dataRange": 1.0,
        "cases": cases,
    }
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "ssim.json")
    with open(path, "w") as f:
        json.dump(out, f)
    print(f"wrote {path}: {len(cases)} cases")
    for c in cases:
        print(f"  {c['name']:20s} {c['width']}x{c['height']} mssim={c['expectedMssim']:.6f}")


if __name__ == "__main__":
    main()
