// Package the Emscripten OpenEXR build (build/<opt>/cairn_openexr.{mjs,wasm})
// into the COMMITTED, self-contained inline module the EXR worker imports:
//
//   ui/src/lib/cairn-plot/image/decoders/wasm-inline/
//     cairn_openexr.js       (copied Emscripten ES6 glue; .js so its .d.ts pairs)
//     cairn_openexr.d.ts     (hand-written factory type — see template below)
//     wasm-exr-inline.ts     (GENERATED: deflated+base64 .wasm + loadExrDecoder)
//
// Same policy as the retired Rust module: the .wasm is RAW-DEFLATEd then
// base64-embedded (the worker is `?worker&inline`d, so base64-of-base64 would
// double high-entropy wasm — we deflate first, inflate at load with the vendored
// synchronous fflate) and instantiated from bytes via Emscripten's
// `instantiateWasm` hook (no fetch — CSP/file:// safe). Consumers need no
// emscripten/cargo.
//
// Run after `build.sh Oz`:  node wasm/openexr/gen-inline.mjs [Oz|O3]

import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";
import { deflateRawSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const opt = process.argv[2] || "Oz";
const build = resolve(here, "build", opt);
const outDir = resolve(here, "../../ui/src/lib/cairn-plot/image/decoders/wasm-inline");
mkdirSync(outDir, { recursive: true });

// 1. Copy the Emscripten glue verbatim (committed) as .js so its sibling
//    cairn_openexr.d.ts is picked up by TS module resolution (a `.mjs` import
//    would require a `.d.mts`).
copyFileSync(resolve(build, "cairn_openexr.mjs"), resolve(outDir, "cairn_openexr.js"));

// 2. Hand-written factory type (Emscripten's --emit-tsd is heavier than we need).
writeFileSync(
  resolve(outDir, "cairn_openexr.d.ts"),
  `/* Hand-written type for the Emscripten OpenEXR glue (cairn_openexr.mjs). */
export interface CairnOpenExrModule {
  _malloc(n: number): number;
  _free(p: number): void;
  _cairn_exr_decode(ptr: number, len: number): number;
  _cairn_exr_free(r: number): void;
  // DEEP live-flatten ABI (depth slider) — see wasm/openexr/src/binding.cpp.
  _cairn_exr_open_deep(ptr: number, len: number): number;
  _cairn_exr_flatten_deep(handle: number, zNear: number, zFar: number): number;
  _cairn_exr_free_open_deep(r: number): void;
  _cairn_exr_free_deep(handle: number): void;
  _cairn_exr_set_deep_budget(bytes: number): void;
  _cairn_exr_deep_gpu_csr(handle: number): number;
  _cairn_exr_free_gpu_csr(r: number): void;
  _cairn_exr_deep_z_range_in_rect(handle: number, x0: number, y0: number, x1: number, y1: number): number;
  _cairn_exr_free_z_range(r: number): void;
  HEAPU8: Uint8Array;
  HEAPU16: Uint16Array;
  HEAP32: Int32Array;
  HEAPF32: Float32Array;
  UTF8ToString(ptr: number): string;
}
export interface CairnOpenExrInit {
  instantiateWasm?(
    imports: WebAssembly.Imports,
    done: (instance: WebAssembly.Instance) => void,
  ): unknown;
}
export default function CairnOpenExr(init?: CairnOpenExrInit): Promise<CairnOpenExrModule>;
`,
);

// 3. Deflate + base64 the .wasm and emit the loader + C-ABI glue.
const wasm = readFileSync(resolve(build, "cairn_openexr.wasm"));
const deflated = deflateRawSync(wasm, { level: 9 });
const b64 = deflated.toString("base64");

const ts = `/**
 * GENERATED by wasm/openexr/gen-inline.mjs — DO NOT EDIT.
 *
 * Self-contained inline OpenEXR (Emscripten) WASM decoder for cairn-plot. Reads
 * LITERALLY every OpenEXR the upstream C++ library can: all compressions incl.
 * HTJ2K (OpenJPH), scanline & tiled, deep (Z-sorted OVER flatten), multi-part,
 * and luminance-chroma (native YC→RGBA). All-HALF sources return raw f16 BIT
 * PATTERNS (Uint16Array, never widened); else f32. See wasm/openexr/.
 *
 * The .wasm is RAW-DEFLATEd + base64-embedded (the worker this ships in is
 * \`?worker&inline\`d — base64-of-base64 doubles high-entropy wasm, so we deflate
 * first and inflate at load with the vendored fflate) and instantiated from
 * bytes via Emscripten's \`instantiateWasm\` hook (no fetch, CSP/file:// safe).
 *
 * .wasm: ${wasm.length} bytes → deflateRaw ${deflated.length} bytes (base64: ${b64.length} chars).
 *
 * Usage:
 *   const { decode_exr } = await loadExrDecoder();
 *   const img = decode_exr(new Uint8Array(exrBytes));
 *   // img.precision === "f16-bits" ? img.halfBits : img.floats; then img.free()
 */
import createOpenExrModule from "./cairn_openexr.js";
import type { CairnOpenExrModule } from "./cairn_openexr.js";
import { inflateSync } from "../vendor/fflate.module.js";

/** The release .wasm, raw-DEFLATEd then base64-encoded. */
export const WASM_EXR_DEFLATED_B64 =
  "${b64}";

/** Decode a base64 string into raw bytes (browser + node, no Buffer/fetch). */
function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** A decoded EXR image, mirroring the retired wasm-bindgen \`DecodedImage\`. */
export interface DecodedImage {
  readonly width: number;
  readonly height: number;
  readonly channels: number;
  readonly precision: "f16-bits" | "f32";
  readonly halfBits: Uint16Array | undefined;
  readonly floats: Float32Array | undefined;
  free(): void;
}

/**
 * A retained DEEP EXR (depth slider). \`handle\` is an opaque wasm-side pointer to
 * the retained samples — pass it to \`flatten_deep(handle, zClip)\` (live, no
 * re-decode) and \`free_deep(handle)\` when the pane unmounts. \`zMin\`/\`zMax\` bound
 * the slider; a non-deep file yields \`null\` from \`open_deep\` (host falls back to
 * the ordinary \`decode_exr\`).
 */
export interface DeepImageOpen {
  readonly handle: number;
  readonly width: number;
  readonly height: number;
  readonly channels: number;
  readonly zMin: number;
  readonly zMax: number;
  readonly totalSamples: number;
}

/** Z range of the samples inside an image-pixel rect (region-select → depth
 *  window). \`count === 0\` means the region held no samples (host no-ops). */
export interface DeepZRange {
  readonly zMin: number;
  readonly zMax: number;
  readonly count: number;
}

/**
 * A deep image's per-pixel Z-SORTED samples, laid out for direct upload to
 * WebGPU storage buffers (the GPU depth-composite path). \`offsets\` are the
 * pixels+1 prefix sums; \`colors\` is 4·total premultiplied RGBA; \`zs\` is the
 * per-sample Z (ascending within each pixel). All JS-owned copies.
 */
export interface DeepGpuCsr {
  readonly width: number;
  readonly height: number;
  readonly total: number;
  readonly offsets: Uint32Array;
  readonly colors: Float32Array;
  readonly zs: Float32Array;
}

// Result struct field order — CONTRACT with wasm/openexr/src/binding.cpp.
const F = { status: 0, width: 1, height: 2, channels: 3, precision: 4, data: 5, dataLen: 6, errCode: 7, errMsg: 8 };
// DeepOpenResult field order (z_min/z_max are FLOATs → read from HEAPF32).
const DF = { status: 0, handle: 1, width: 2, height: 3, channels: 4, zMin: 5, zMax: 6, total: 7, errCode: 8, errMsg: 9 };
// DeepGpuCsr field order — CONTRACT with wasm/openexr/src/binding.cpp.
const GF = { status: 0, offsets: 1, colors: 2, z: 3, total: 4, width: 5, height: 6, errCode: 7, errMsg: 8 };
// DeepZRange field order (z_min/z_max are FLOATs → read from HEAPF32).
const ZR = { status: 0, zMin: 1, zMax: 2, count: 3, errCode: 4, errMsg: 5 };

/** Read a DecodeResult* out of the module heap into a JS-owned DecodedImage
 *  (copies the payload out of wasm memory, then frees the wasm-side result). */
function readDecodeResult(mod: CairnOpenExrModule, rPtr: number): DecodedImage {
  const H = mod.HEAP32;
  const base = rPtr >> 2;
  if (H[base + F.status] !== 0) {
    const code = mod.UTF8ToString(H[base + F.errCode]!);
    const msg = mod.UTF8ToString(H[base + F.errMsg]!);
    mod._cairn_exr_free(rPtr);
    const err = new Error(msg) as Error & { code: string };
    err.name = "CairnExrDecodeError";
    err.code = code;
    throw err;
  }
  const width = H[base + F.width]!;
  const height = H[base + F.height]!;
  const channels = H[base + F.channels]!;
  const isHalf = H[base + F.precision] === 0;
  const dataPtr = H[base + F.data]! >>> 0;
  const dataLen = H[base + F.dataLen]!;
  // .slice() copies out of wasm linear memory into a JS-owned, transferable
  // typed array that outlives the free() below.
  const halfBits = isHalf
    ? mod.HEAPU16.slice(dataPtr >> 1, (dataPtr >> 1) + dataLen)
    : undefined;
  const floats = isHalf
    ? undefined
    : mod.HEAPF32.slice(dataPtr >> 2, (dataPtr >> 2) + dataLen);
  mod._cairn_exr_free(rPtr);
  return {
    width,
    height,
    channels,
    precision: isHalf ? "f16-bits" : "f32",
    halfBits,
    floats,
    free() {},
  };
}

/** Decode EXR bytes (one-shot; deep files are flattened at full composite). */
function readResult(mod: CairnOpenExrModule, bytes: Uint8Array): DecodedImage {
  const inPtr = mod._malloc(bytes.length);
  mod.HEAPU8.set(bytes, inPtr);
  const rPtr = mod._cairn_exr_decode(inPtr, bytes.length);
  mod._free(inPtr);
  return readDecodeResult(mod, rPtr);
}

/** Open + RETAIN a DEEP EXR behind a wasm-side handle. Returns \`null\` when the
 *  file is NOT deep (the caller then uses \`decode_exr\`); throws on a genuinely
 *  broken deep file. */
function openDeep(mod: CairnOpenExrModule, bytes: Uint8Array): DeepImageOpen | null {
  const inPtr = mod._malloc(bytes.length);
  mod.HEAPU8.set(bytes, inPtr);
  const rPtr = mod._cairn_exr_open_deep(inPtr, bytes.length);
  mod._free(inPtr);
  const H = mod.HEAP32;
  const Hf = mod.HEAPF32;
  const base = rPtr >> 2;
  if (H[base + DF.status] !== 0) {
    const code = mod.UTF8ToString(H[base + DF.errCode]!);
    const msg = mod.UTF8ToString(H[base + DF.errMsg]!);
    mod._cairn_exr_free_open_deep(rPtr);
    if (code === "not-deep") return null; // not a deep file → caller uses decode_exr
    const err = new Error(msg) as Error & { code: string };
    err.name = "CairnExrDecodeError";
    err.code = code;
    throw err;
  }
  const out: DeepImageOpen = {
    handle: H[base + DF.handle]! >>> 0,
    width: H[base + DF.width]!,
    height: H[base + DF.height]!,
    channels: H[base + DF.channels]!,
    zMin: Hf[base + DF.zMin]!,
    zMax: Hf[base + DF.zMax]!,
    totalSamples: H[base + DF.total]! >>> 0,
  };
  mod._cairn_exr_free_open_deep(rPtr);
  return out;
}

/** Flatten a retained deep handle over the Z WINDOW [\`zNear\`, \`zFar\`], live.
 *  \`zNear = -Infinity\` ⇒ the legacy single far-cutoff. */
function flattenDeep(
  mod: CairnOpenExrModule,
  handle: number,
  zNear: number,
  zFar: number,
): DecodedImage {
  const rPtr = mod._cairn_exr_flatten_deep(handle, zNear, zFar);
  return readDecodeResult(mod, rPtr);
}

/** Release a retained deep handle (frees its retained samples / cached bytes). */
function freeDeep(mod: CairnOpenExrModule, handle: number): void {
  mod._cairn_exr_free_deep(handle);
}

/** Z range of the samples inside an image-pixel rect (region-select). */
function deepZRangeInRect(
  mod: CairnOpenExrModule,
  handle: number,
  x0: number,
  y0: number,
  x1: number,
  y1: number,
): DeepZRange {
  const rPtr = mod._cairn_exr_deep_z_range_in_rect(handle, x0, y0, x1, y1);
  const H = mod.HEAP32;
  const Hf = mod.HEAPF32;
  const base = rPtr >> 2;
  if (H[base + ZR.status] !== 0) {
    const code = mod.UTF8ToString(H[base + ZR.errCode]!);
    const msg = mod.UTF8ToString(H[base + ZR.errMsg]!);
    mod._cairn_exr_free_z_range(rPtr);
    const err = new Error(msg) as Error & { code: string };
    err.name = "CairnExrDecodeError";
    err.code = code;
    throw err;
  }
  const out: DeepZRange = {
    zMin: Hf[base + ZR.zMin]!,
    zMax: Hf[base + ZR.zMax]!,
    count: H[base + ZR.count]! >>> 0,
  };
  mod._cairn_exr_free_z_range(rPtr);
  return out;
}

/** Export a retained deep handle's Z-sorted samples for GPU upload. Copies the
 *  three arrays out of wasm memory (JS-owned), then frees the wasm-side result. */
function deepGpuCsr(mod: CairnOpenExrModule, handle: number): DeepGpuCsr {
  const rPtr = mod._cairn_exr_deep_gpu_csr(handle);
  const H = mod.HEAP32;
  const base = rPtr >> 2;
  if (H[base + GF.status] !== 0) {
    const code = mod.UTF8ToString(H[base + GF.errCode]!);
    const msg = mod.UTF8ToString(H[base + GF.errMsg]!);
    mod._cairn_exr_free_gpu_csr(rPtr);
    const err = new Error(msg) as Error & { code: string };
    err.name = "CairnExrDecodeError";
    err.code = code;
    throw err;
  }
  const width = H[base + GF.width]!;
  const height = H[base + GF.height]!;
  const total = H[base + GF.total]! >>> 0;
  const offsetsPtr = H[base + GF.offsets]! >>> 0;
  const colorsPtr = H[base + GF.colors]! >>> 0;
  const zPtr = H[base + GF.z]! >>> 0;
  const offsets = mod.HEAPU8.slice(offsetsPtr, offsetsPtr + (width * height + 1) * 4);
  const colors = mod.HEAPU8.slice(colorsPtr, colorsPtr + total * 4 * 4);
  const zbytes = mod.HEAPU8.slice(zPtr, zPtr + total * 4);
  mod._cairn_exr_free_gpu_csr(rPtr);
  return {
    width,
    height,
    total,
    offsets: new Uint32Array(offsets.buffer, offsets.byteOffset, width * height + 1),
    colors: new Float32Array(colors.buffer, colors.byteOffset, total * 4),
    zs: new Float32Array(zbytes.buffer, zbytes.byteOffset, total),
  };
}

let ready: Promise<CairnOpenExrModule> | null = null;

/** The decoder surface returned by {@link loadExrDecoder}. */
export interface ExrDecoder {
  decode_exr: (bytes: Uint8Array) => DecodedImage;
  /** Open + retain a deep EXR (null when not deep). */
  open_deep: (bytes: Uint8Array) => DeepImageOpen | null;
  /** Flatten a retained deep handle over the Z window [\`zNear\`, \`zFar\`].
   *  \`zNear = -Infinity, zFar = Infinity\` = full composite. */
  flatten_deep: (handle: number, zNear: number, zFar: number) => DecodedImage;
  /** Free a retained deep handle. */
  free_deep: (handle: number) => void;
  /** Set the global deep-retention LRU byte budget (default 512 MB). */
  set_deep_budget: (bytes: number) => void;
  /** Export a deep handle's Z-sorted samples for GPU upload (storage buffers). */
  deep_gpu_csr: (handle: number) => DeepGpuCsr;
  /** Z range of the samples inside an image-pixel rect (region-select). */
  deep_z_range_in_rect: (handle: number, x0: number, y0: number, x1: number, y1: number) => DeepZRange;
  DecodedImage: unknown;
}

/**
 * Instantiate the OpenEXR decoder once (idempotent) from the embedded bytes and
 * return the decode surface. No network / filesystem access.
 */
export async function loadExrDecoder(): Promise<ExrDecoder> {
  const pending =
    ready ??
    (ready = createOpenExrModule({
      instantiateWasm(imports, done) {
        // Instantiate from bytes (never fetch): CSP- and file://-safe. The
        // \`as unknown as BufferSource\` both selects the {module,instance}
        // overload and sidesteps TS's ArrayBufferLike↔ArrayBuffer variance.
        const wasmBytes = inflateSync(base64ToBytes(WASM_EXR_DEFLATED_B64));
        void WebAssembly.instantiate(wasmBytes as unknown as BufferSource, imports).then(
          (result) => done((result as WebAssembly.WebAssemblyInstantiatedSource).instance),
        );
        return {};
      },
    }));
  const mod = await pending;
  return {
    decode_exr: (bytes: Uint8Array) => readResult(mod, bytes),
    open_deep: (bytes: Uint8Array) => openDeep(mod, bytes),
    flatten_deep: (handle: number, zNear: number, zFar: number) => flattenDeep(mod, handle, zNear, zFar),
    free_deep: (handle: number) => freeDeep(mod, handle),
    set_deep_budget: (bytes: number) => mod._cairn_exr_set_deep_budget(bytes),
    deep_gpu_csr: (handle: number) => deepGpuCsr(mod, handle),
    deep_z_range_in_rect: (handle: number, x0: number, y0: number, x1: number, y1: number) =>
      deepZRangeInRect(mod, handle, x0, y0, x1, y1),
    DecodedImage: class {},
  };
}
`;

writeFileSync(resolve(outDir, "wasm-exr-inline.ts"), ts);

console.log(
  `wrote inline module (${opt}): ${resolve(outDir, "wasm-exr-inline.ts")}\n` +
    `  .wasm ${wasm.length} bytes -> deflateRaw ${deflated.length} bytes -> base64 ${b64.length} chars`,
);
