/**
 * `toolbar-menu-portal.browser.ts` — regression harness for the toolbar
 * dropdown Z-ORDER / stacking bug (NOT a jsdom unit test — the defect is a real
 * CSS stacking-context/overflow issue, so it needs a live browser with layout).
 *
 * ## The bug this pins
 * Pane roots carry `isolation: isolate` (so the pixel-value overlay can't leak
 * over the host header). An open `ToolbarMenu` dropdown used to render INLINE in
 * the toolbar (`position:absolute` inside the pane). When the dropdown was
 * TALLER than its pane, the portion overflowing the pane bottom was painted OVER
 * by the NEXT pane below (a later-DOM sibling with its own stacking context) —
 * the overflowing options were invisible / not hit-testable. The fix PORTALS the
 * open dropdown to `document.body` as a `position:fixed` box at a very high
 * z-index, so it escapes every pane's isolated stacking context and floats above
 * sibling panes.
 *
 * ## What the harness asserts (SELF-DRIVING — runs under `npm run test:harness`)
 * Two panes stacked vertically (A above B), each `isolation:isolate`. Pane A is
 * SHORT and its toolbar menu, when open, is TALLER than A and overflows into B's
 * area. Opening A's menu:
 *   1. the open list is a child of `document.body` (portaled), `position:fixed`,
 *      high z-index;
 *   2. it is NOT occluded by pane B — `elementFromPoint` at a menu option that
 *      overlaps B's box returns the option (inside the list), NOT pane B's fill;
 *   3. a pointer-down INSIDE the list does NOT close it;
 *   4. selecting an option fires `onSelect` AND closes;
 *   5. Escape closes; an OUTSIDE pointer-down closes.
 *
 * RUNNING (headless is the gate; the runner bundles + serves this):
 *   npm run test:harness -- --only toolbar-menu-portal
 * The generated `.browser.bundle.js` is gitignored — regenerated by the runner.
 */
import React from "react";
import { createRoot } from "react-dom/client";
import PlotToolbar from "../PlotToolbar";
import type { PlotController, ControllerCapabilities } from "../../controls/types";
import type { ToolbarConfig } from "../../controls/ToolbarConfig";
import { createHarness } from "../../testing/harness";

const h = React.createElement;

const { report, setOverallStatus } = createHarness({ title: "MENU PORTAL" });

const allCaps: ControllerCapabilities = {
  zoom: true, pan: true, boxZoom: true, select: true, lasso: true,
  autoscale: true, reset: true, screenshot: true, hover: true, spikelines: true,
  hoverModes: true, legend: true, axisScaleToggle: true, perAxisDrag: true,
  brush: true, reorder: true,
};
function makeController(): PlotController {
  return {
    capabilities: allCaps, dragMode: "pan", hoverMode: "closest", spikelines: false,
    isModified: true, setDragMode() {}, setHoverMode() {}, toggleSpikelines() {},
    zoomIn() {}, zoomOut() {}, autoscale() {}, reset() {},
    toPNG: () => Promise.resolve(new Blob()),
  };
}

// A tall menu: many options so the OPEN dropdown is taller than pane A (which is
// intentionally short) and overflows into pane B.
const OPTIONS = [
  { id: "o1", label: "Option One" },
  { id: "o2", label: "Option Two" },
  { id: "o3", label: "Option Three" },
  { id: "o4", label: "Option Four" },
  { id: "o5", label: "Option Five" },
  { id: "o6", label: "Option Six" },
  { id: "o7", label: "Option Seven" },
  { id: "o8", label: "Option Eight" },
];

let selected = "o1";
let onSelectCount = 0;

function buildConfig(): ToolbarConfig {
  return {
    visibility: "always",
    position: "top-left", // open a LEFT-aligned dropdown near the pane's left edge
    leadingButtons: [
      {
        id: "menu",
        title: "Tall menu",
        menu: {
          value: selected,
          onSelect: (id) => { selected = id; onSelectCount++; render(); },
          options: OPTIONS,
        },
      },
    ],
  };
}

const paneA = document.getElementById("paneA") as HTMLElement;
const root = createRoot(paneA);
function render(): void {
  root.render(h(PlotToolbar, { controller: makeController(), config: buildConfig() }));
}

// A second toolbar mounted in the LIGHT-scoped pane (its own menu), to prove the
// portal follows its ORIGIN pane's theme (not the document default): the dark
// pane's menu renders dark, this one light — both under the same <body>.
let selectedL = "o1";
function buildConfigL(): ToolbarConfig {
  return {
    visibility: "always",
    position: "top-left",
    leadingButtons: [
      {
        id: "menuL",
        title: "Light menu",
        menu: { value: selectedL, onSelect: (id) => { selectedL = id; renderL(); }, options: OPTIONS },
      },
    ],
  };
}
const paneL = document.getElementById("paneL") as HTMLElement;
const rootL = createRoot(paneL);
function renderL(): void {
  rootL.render(h(PlotToolbar, { controller: makeController(), config: buildConfigL() }));
}
const menuTriggerL = () => paneL.querySelector<HTMLButtonElement>('button[aria-haspopup="listbox"]');
async function openMenuL(): Promise<void> {
  const t = menuTriggerL();
  if (t && t.getAttribute("aria-expanded") !== "true") click(t);
  await wait(60);
}
const rgb = (el: Element) => getComputedStyle(el).backgroundColor.replace(/\s+/g, " ").trim();

function fire(el: Element, type: string): void {
  el.dispatchEvent(new MouseEvent(type, { bubbles: true, cancelable: true, view: window }));
}
function click(el: Element): void {
  for (const t of ["pointerdown", "mousedown", "mouseup", "click"]) fire(el, t);
}
function firePointerAt(el: Element): void {
  fire(el, "pointerdown");
}
function pressEscape(): void {
  document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true, cancelable: true }));
}
const wait = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

const menuTrigger = () => paneA.querySelector<HTMLButtonElement>('button[aria-haspopup="listbox"]');
const listbox = () => document.querySelector<HTMLUListElement>('ul[role="listbox"]');
const expanded = () => menuTrigger()?.getAttribute("aria-expanded") === "true";

async function openMenu(): Promise<void> {
  const t = menuTrigger();
  if (t && t.getAttribute("aria-expanded") !== "true") click(t);
  await wait(60);
}

async function main(): Promise<void> {
  let ok = true;
  const gate = (cond: boolean, msg: string) => { report(cond, msg); ok = ok && cond; };
  try {
    render();
    renderL();
    await wait(200);

    const paneB = document.getElementById("paneB") as HTMLElement;
    const paneBFill = document.getElementById("paneB-fill") as HTMLElement;

    gate(!!menuTrigger(), "[0] leading MENU trigger present (toolbar not folded)");

    // --- open + portal/fixed/z assertions ---------------------------------
    await openMenu();
    gate(expanded(), "[1] menu opens on click");
    const ul = listbox();
    gate(!!ul, "[2] the open list is in the DOM");
    if (!ul) { setOverallStatus(false); return; }

    gate(ul.parentElement === document.body, "[3] open list is portaled to document.body");
    const cs = getComputedStyle(ul);
    gate(cs.position === "fixed", `[4] list is position:fixed (got ${cs.position})`);
    gate(Number(cs.zIndex) >= 1000, `[5] list has a high z-index (got ${cs.zIndex})`);

    // --- the crux: NOT occluded by pane B --------------------------------
    // The dropdown is taller than pane A, so some option centers fall inside
    // pane B's box. Pane B is filled with an opaque div; without the portal it
    // (a later-DOM, separately-stacked sibling) would paint OVER those options.
    const bRect = paneB.getBoundingClientRect();
    const ulRect = ul.getBoundingClientRect();
    gate(
      ulRect.bottom > bRect.top + 2,
      `[6] the open dropdown overflows pane A into pane B's area (list bottom ${Math.round(ulRect.bottom)} vs pane B top ${Math.round(bRect.top)})`,
    );

    const options = Array.from(ul.querySelectorAll<HTMLButtonElement>('li[role="option"] button'));
    // The options whose CENTER lands inside pane B's vertical span — these are
    // exactly the ones the old inline-absolute dropdown lost behind pane B.
    const overlapping = options.filter((o) => {
      const r = o.getBoundingClientRect();
      const cy = r.top + r.height / 2;
      const cx = r.left + r.width / 2;
      return cy >= bRect.top && cy <= bRect.bottom && cx >= bRect.left && cx <= bRect.right;
    });
    gate(overlapping.length > 0, `[7] at least one option overlaps pane B (${overlapping.length} do)`);

    let notOccluded = overlapping.length > 0;
    let occludedLabel = "";
    for (const o of overlapping) {
      const r = o.getBoundingClientRect();
      const cx = r.left + r.width / 2;
      const cy = r.top + r.height / 2;
      const hit = document.elementFromPoint(cx, cy);
      const usable = !!hit && (hit === o || o.contains(hit) || ul.contains(hit));
      const isPaneB = !!hit && (hit === paneBFill || paneBFill.contains(hit) || hit === paneB);
      if (!usable || isPaneB) {
        notOccluded = false;
        occludedLabel = (o.textContent ?? "").trim();
        break;
      }
    }
    gate(
      notOccluded,
      notOccluded
        ? `[8] every option over pane B is hit-testable (NOT occluded by pane B)`
        : `[8] option "${occludedLabel}" is OCCLUDED by pane B (elementFromPoint returned pane B content)`,
    );

    // --- inside pointer-down keeps it open --------------------------------
    firePointerAt(ul);
    await wait(40);
    gate(expanded(), "[9] pointer-down INSIDE the list keeps it open");

    // --- selecting an option fires onSelect AND closes --------------------
    const before = onSelectCount;
    const pick = overlapping[0] ?? options[options.length - 1];
    click(pick);
    await wait(60);
    gate(onSelectCount === before + 1, `[10] selecting an option fires onSelect (count ${before} -> ${onSelectCount})`);
    gate(!expanded(), "[11] selecting an option closes the menu");

    // --- Escape closes -----------------------------------------------------
    await openMenu();
    gate(expanded(), "[12] menu re-opens");
    pressEscape();
    await wait(40);
    gate(!expanded(), "[13] Escape closes the menu");

    // --- outside pointer-down closes --------------------------------------
    await openMenu();
    gate(expanded(), "[14] menu re-opens (for outside-click)");
    const outside = document.getElementById("outside") as HTMLElement;
    firePointerAt(outside);
    await wait(40);
    gate(!expanded(), "[15] an OUTSIDE pointer-down closes the menu");

    // --- theme follows the ORIGIN pane (dark vs light, same <body>) --------
    // The portaled list can't inherit the pane's tokens from document.body; the
    // themed-portal helper copies them. Open the DARK pane's menu and the LIGHT
    // pane's menu (both portal to body) and assert each renders with its
    // origin's elevated-surface token.
    // Open the DARK pane's menu and read its portaled list's background BEFORE
    // touching the light pane (clicking the light trigger is an outside-click for
    // the dark menu and closes it).
    await openMenu(); // dark pane A
    const darkUl = listbox();
    const darkBg = darkUl ? rgb(darkUl) : "";
    gate(!!darkUl, "[16] dark pane's menu opens (portaled list present)");

    await openMenuL(); // light pane L (closes the dark menu)
    await wait(40);
    const lightUl = listbox();
    const lightBg = lightUl ? rgb(lightUl) : "";
    gate(!!lightUl && lightUl !== darkUl, "[17] light pane's menu opens (a DIFFERENT portaled list)");

    // dark --color-bg-elevated-rgb = 22 27 34; light = 246 248 250.
    gate(darkBg === "rgb(22, 27, 34)", `[18] DARK pane's portaled menu renders with the DARK token (bg ${darkBg})`);
    gate(lightBg === "rgb(246, 248, 250)", `[19] LIGHT pane's portaled menu renders with the LIGHT token (bg ${lightBg})`);
    gate(darkBg !== lightBg && darkBg !== "", `[20] the two portals differ — theme FOLLOWS its origin, not the document default`);

    setOverallStatus(ok);
  } catch (err) {
    report(false, `threw: ${err instanceof Error ? (err.stack ?? err.message) : String(err)}`);
    setOverallStatus(false);
  }
}

void main();
