/**
 * REAL-FILE end-to-end harness for HDR gain-map JPEG decoding. Node's test
 * runner has no JPEG codec (createImageBitmap), so the full base+gain decode +
 * float reconstruction can only run in a browser — this page drives it headless
 * (like the engine parity harnesses) and reports PASS/FAIL via `#status`.
 *
 * It decodes the committed 1000x667 Adobe hdr-gain-map fixture through the
 * public `decodeImage` and asserts:
 *   (a) the result is a FLOAT image (kind "f32"), not the SDR uint8 base;
 *   (b) shape matches the base (1000x667, 3 channels);
 *   (c) headroom is present: max channel > 1 and roughly <= 2^HDRCapacityMax·(1+off);
 *   (d) it EQUALS an independent reconstruction from the separately-decoded
 *       base + gain + parsed metadata (pins the MPF-extract → two-JPEG-decode →
 *       reconstruct wiring), and a darkest-gain (near-neutral) pixel stays close
 *       to its linearized base value (neutral round-trip on real data);
 *   (e) a synthesized PLAIN JPEG still decodes to uint8 (graceful non-branch).
 *
 * RUNNING (mirrors deep-composite.browser.ts):
 *   1. Bundle:
 *        cd cairn/ui && npx esbuild \
 *          src/plots/image/model/decoders/__tests__/gain-map-decode.browser.ts \
 *          --bundle --format=esm \
 *          --outfile=src/plots/image/model/decoders/__tests__/gain-map-decode.browser.bundle.js
 *   2. Serve over http FROM THE ui/ ROOT and open the .browser.html in Chrome,
 *      or drive it headless:
 *        npm run test:harness -- --all --only gain-map
 *
 * The generated `.bundle.js` is NOT committed (gitignored) — regenerated by the
 * runner.
 */
import { decodeImage } from "../../decoders.ts";
import {
  parseMpfSecondImage,
  extractXmp,
  parseGainMapMetadata,
  reconstructHdrFromGainMap,
  type RgbaImage,
} from "../gain-map.ts";
import { createHarness } from "../../../../../testing/harness";

const FIXTURE_URL = new URL("../fixtures/gainmap-benz-1000x667.jpg", import.meta.url).href;

const { report, setOverallStatus } = createHarness({ title: "GAINMAP DECODE" });

function info(message: string): void {
  console.log(message);
  const el = document.getElementById("result");
  if (el) {
    const p = document.createElement("div");
    p.textContent = message;
    p.style.color = "#0366d6";
    el.appendChild(p);
  }
}

function srgbToLinear(c: number): number {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

async function blobToRgba(blob: Blob): Promise<RgbaImage> {
  const bitmap = await createImageBitmap(blob);
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const ctx = canvas.getContext("2d")!;
  ctx.drawImage(bitmap, 0, 0);
  const img = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
  bitmap.close();
  return { data: img.data, width: img.width, height: img.height };
}

/** A tiny valid PLAIN JPEG (canvas → image/jpeg blob → bytes). */
async function makePlainJpegBytes(): Promise<ArrayBuffer> {
  const canvas = new OffscreenCanvas(8, 8);
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "#3366cc";
  ctx.fillRect(0, 0, 8, 8);
  const blob = await canvas.convertToBlob({ type: "image/jpeg" });
  return blob.arrayBuffer();
}

async function run(): Promise<void> {
  let allPass = true;
  const check = (cond: boolean, msg: string): void => {
    if (!cond) allPass = false;
    report(cond, msg);
  };

  // --- (a)(b) decode the real fixture → FLOAT, correct shape ---------------
  const bytes = await (await fetch(FIXTURE_URL)).arrayBuffer();
  const decoded = await decodeImage({ bytes, mime: "image/jpeg" });
  check(decoded.kind === "f32", `real gain-map JPEG decodes to FLOAT (kind=${decoded.kind})`);
  if (decoded.kind !== "f32") {
    setOverallStatus(false);
    return;
  }
  check(decoded.width === 1000 && decoded.height === 667, `shape ${decoded.width}x${decoded.height} == 1000x667`);
  check(decoded.channels === 3, `channels=${decoded.channels} == 3`);
  check(decoded.precision === "f32" && decoded.data instanceof Float32Array, `precision f32 Float32Array`);
  const data = decoded.data as Float32Array;

  // --- (c) headroom present, bounded by ~2^HDRCapacityMax ------------------
  let max = -Infinity;
  let min = Infinity;
  for (let i = 0; i < data.length; i++) {
    const v = data[i]!;
    if (v > max) max = v;
    if (v < min) min = v;
  }
  const off = 0.015625;
  const ceil = Math.pow(2, 2.6) * (1 + off) + 0.05; // ~6.16
  info(`value range: min=${min.toFixed(5)} max=${max.toFixed(4)} (ceil≈${ceil.toFixed(3)})`);
  check(max > 1, `max ${max.toFixed(4)} > 1 (HDR headroom present)`);
  check(max <= ceil, `max ${max.toFixed(4)} <= 2^2.6·(1+off) (${ceil.toFixed(3)})`);
  check(min > -0.05, `min ${min.toFixed(5)} > -0.05 (offsets only slightly negative)`);

  // --- (d) parity with an independent reconstruction + neutral round-trip --
  const u8 = new Uint8Array(bytes);
  const range = parseMpfSecondImage(u8)!;
  const gainBytes = bytes.slice(range.offset, range.offset + range.size);
  const meta = parseGainMapMetadata(extractXmp(new Uint8Array(gainBytes))!)!;
  const base = await blobToRgba(new Blob([bytes], { type: "image/jpeg" }));
  const gain = await blobToRgba(new Blob([gainBytes], { type: "image/jpeg" }));
  const ref = reconstructHdrFromGainMap(base, gain, meta);
  let maxAbsDiff = 0;
  for (let i = 0; i < ref.length; i++) maxAbsDiff = Math.max(maxAbsDiff, Math.abs(ref[i]! - data[i]!));
  check(ref.length === data.length && maxAbsDiff < 1e-4, `decodeImage == independent reconstruction (maxAbsDiff=${maxAbsDiff.toExponential(2)})`);

  // Neutral round-trip on real data: find the pixel whose gain samples are the
  // darkest (recovery≈0 ⇒ factor≈2^GainMapMin, near-neutral) and confirm the
  // reconstructed value tracks its LINEARIZED base (within the residual
  // 2^GainMapMin attenuation, which is ~0.9x here) — i.e. driven by the base,
  // not a constant.
  let bestIdx = 0;
  let bestGain = Infinity;
  for (let p = 0; p < base.width * base.height; p++) {
    const g = gain.data[p * 4]! + gain.data[p * 4 + 1]! + gain.data[p * 4 + 2]!;
    if (g < bestGain) {
      bestGain = g;
      bestIdx = p;
    }
  }
  const baseLinR = srgbToLinear(base.data[bestIdx * 4]! / 255);
  const outR = data[bestIdx * 3]!;
  const ratio = baseLinR > 1e-4 ? outR / baseLinR : 1;
  info(`darkest-gain px#${bestIdx}: baseLin=${baseLinR.toFixed(4)} out=${outR.toFixed(4)} ratio=${ratio.toFixed(3)}`);
  check(ratio > 0.8 && ratio < 1.15, `neutral-ish pixel tracks linearized base (ratio ${ratio.toFixed(3)} ∈ [0.8,1.15])`);

  // --- (e) plain JPEG still uint8 -----------------------------------------
  const plainBytes = await makePlainJpegBytes();
  const plain = await decodeImage({ bytes: plainBytes, mime: "image/jpeg" });
  check(plain.kind === "u8", `plain JPEG (no gain map) stays uint8 (kind=${plain.kind})`);

  setOverallStatus(allPass);
}

run().catch((err) => {
  report(false, `threw: ${err?.stack ?? err}`);
  setOverallStatus(false);
});
