/**
 * Deep depth-slider tests for the OpenEXR-wasm decoder. Drives the DEEP
 * live-flatten ABI (`open_deep` → `flatten_deep(zClip)` → `free_deep`) through
 * the committed inline module against the committed deep fixture
 * (`deep-rgba-32x32.exr`, generated by wasm/openexr/fixtures/gen.cpp):
 *
 *   2-sample pixels ((x+y)%3==0): a BACK sample at Z=10 (opaque, a=1) written
 *   FIRST + a FRONT sample at Z=1 (semi-transparent, a=0.5) written second.
 *   1-sample pixels sit at Z=5. So a correct flatten must sort by Z, and a
 *   cutoff BETWEEN the two (zClip=7) must drop the back and keep only the front.
 *
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/image/decoders/exr-deep-flatten.test.ts
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { loadExrDecoder } from "./wasm-inline/wasm-exr-inline.ts";

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));
}

/** IEEE-754 binary16 bit pattern → JS number. */
function h2f(b: number): number {
  const s = (b & 0x8000) >> 15;
  const e = (b & 0x7c00) >> 10;
  const f = b & 0x03ff;
  let v: number;
  if (e === 0) v = (f / 1024) * 2 ** -14;
  else if (e === 0x1f) v = f ? NaN : Infinity;
  else v = (1 + f / 1024) * 2 ** (e - 15);
  return s ? -v : v;
}

const W = 32;
const H = 32;
const twoSample = (x: number, y: number) => (x + y) % 3 === 0;

test("open_deep reports the Z range + dims of the deep fixture", async () => {
  const { open_deep, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"));
  assert.ok(deep, "expected a deep handle");
  assert.equal(deep!.width, W);
  assert.equal(deep!.height, H);
  assert.equal(deep!.channels, 4);
  assert.equal(deep!.zMin, 1);
  assert.equal(deep!.zMax, 10);
  assert.ok(deep!.totalSamples > W * H, "at least one sample per pixel");
  free_deep(deep!.handle);
});

test("open_deep returns null for a non-deep EXR (host falls back to decode_exr)", async () => {
  const { open_deep } = await loadExrDecoder();
  assert.equal(open_deep(fixture("rgb-zip-half-64x48.exr")), null);
});

test("flatten_deep(zMax) matches the one-shot decode_exr bit-for-bit", async () => {
  const { decode_exr, open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  const full = decode_exr(fixture("deep-rgba-32x32.exr"));
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  const flat = flatten_deep(deep.handle, deep.zMax);
  assert.equal(flat.precision, "f16-bits");
  assert.deepEqual(Array.from(flat.halfBits!), Array.from(full.halfBits!));
  free_deep(deep.handle);
});

test("flatten_deep with zClip between front and back yields ONLY the front", async () => {
  const { open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  const full = flatten_deep(deep.handle, deep.zMax); // both samples
  const clip = flatten_deep(deep.handle, 7); // drops the back (Z=10), keeps front (Z=1) + single (Z=5)
  const fh = full.halfBits!;
  const ch = clip.halfBits!;

  let twoCount = 0;
  let oneCount = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const i = (y * W + x) * 4;
      const aFull = h2f(fh[i + 3]!);
      const aClip = h2f(ch[i + 3]!);
      if (twoSample(x, y)) {
        twoCount++;
        // Full composites front(a=0.5) OVER back(a=1) → total alpha 1.0; the
        // Z=7 cut keeps only the semi-transparent front → alpha 0.5.
        assert.ok(Math.abs(aFull - 1.0) < 1e-3, `full alpha≈1 at (${x},${y}), got ${aFull}`);
        assert.ok(Math.abs(aClip - 0.5) < 1e-3, `clip alpha≈0.5 at (${x},${y}), got ${aClip}`);
      } else {
        oneCount++;
        // Single sample at Z=5 (≤ 7) is in BOTH composites → identical bits.
        for (let c = 0; c < 4; c++) {
          assert.equal(ch[i + c], fh[i + c], `single-sample pixel (${x},${y}) ch ${c} differs`);
        }
      }
    }
  }
  assert.ok(twoCount > 0 && oneCount > 0, "fixture must have both pixel kinds");
  free_deep(deep.handle);
});

test("evicted (over-budget → redecode) handle flattens identically to retained", async () => {
  const { decode_exr, open_deep, flatten_deep, free_deep, set_deep_budget } =
    await loadExrDecoder();
  const full = decode_exr(fixture("deep-rgba-32x32.exr"));
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  try {
    // Force the global LRU budget to 0 → every retained handle (incl. this one)
    // is evicted to redecode-from-cached-bytes mode. Correctness must not change.
    set_deep_budget(0);
    const flat = flatten_deep(deep.handle, deep.zMax);
    assert.deepEqual(Array.from(flat.halfBits!), Array.from(full.halfBits!));
    // A mid-Z cut still yields only the front (α 0.5) on 2-sample pixels.
    const clip = flatten_deep(deep.handle, 7);
    const ch = clip.halfBits!;
    let checked = 0;
    for (let y = 0; y < H; y++) {
      for (let x = 0; x < W; x++) {
        if (!twoSample(x, y)) continue;
        checked++;
        assert.ok(Math.abs(h2f(ch[(y * W + x) * 4 + 3]!) - 0.5) < 1e-3);
      }
    }
    assert.ok(checked > 0);
  } finally {
    free_deep(deep.handle);
    set_deep_budget(512 * 1024 * 1024); // restore default for other tests
  }
});
