/**
 * Deep depth-slider tests for the OpenEXR-wasm decoder. Drives the DEEP
 * live-flatten ABI (`open_deep` → `flatten_deep(zClip)` → `free_deep`) through
 * the committed inline module against the committed deep fixture
 * (`deep-rgba-32x32.exr`, generated by wasm/openexr/fixtures/gen.cpp):
 *
 *   2-sample pixels ((x+y)%3==0): a BACK sample at Z=10 (opaque, a=1) written
 *   FIRST + a FRONT sample at Z=1 (semi-transparent, a=0.5) written second.
 *   1-sample pixels sit at Z=5. So a correct flatten must sort by Z, and a
 *   cutoff BETWEEN the two (zClip=7) must drop the back and keep only the front.
 *
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/image/decoders/exr-deep-flatten.test.ts
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { loadExrDecoder } from "./wasm-inline/wasm-exr-inline.ts";

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));
}

/** IEEE-754 binary16 bit pattern → JS number. */
function h2f(b: number): number {
  const s = (b & 0x8000) >> 15;
  const e = (b & 0x7c00) >> 10;
  const f = b & 0x03ff;
  let v: number;
  if (e === 0) v = (f / 1024) * 2 ** -14;
  else if (e === 0x1f) v = f ? NaN : Infinity;
  else v = (1 + f / 1024) * 2 ** (e - 15);
  return s ? -v : v;
}

const W = 32;
const H = 32;
const twoSample = (x: number, y: number) => (x + y) % 3 === 0;

test("open_deep reports the Z range + dims of the deep fixture", async () => {
  const { open_deep, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"));
  assert.ok(deep, "expected a deep handle");
  assert.equal(deep!.width, W);
  assert.equal(deep!.height, H);
  assert.equal(deep!.channels, 4);
  assert.equal(deep!.zMin, 1);
  assert.equal(deep!.zMax, 10);
  assert.ok(deep!.totalSamples > W * H, "at least one sample per pixel");
  free_deep(deep!.handle);
});

test("open_deep returns null for a non-deep EXR (host falls back to decode_exr)", async () => {
  const { open_deep } = await loadExrDecoder();
  assert.equal(open_deep(fixture("rgb-zip-half-64x48.exr")), null);
});

test("full window flatten_deep matches the one-shot decode_exr bit-for-bit", async () => {
  const { decode_exr, open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  const full = decode_exr(fixture("deep-rgba-32x32.exr"));
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  // (-inf, +inf) and the exact [zMin, zMax] window BOTH include every sample →
  // both must reproduce the one-shot full composite bit-for-bit.
  const openWin = flatten_deep(deep.handle, -Infinity, Infinity);
  const exactWin = flatten_deep(deep.handle, deep.zMin, deep.zMax);
  assert.equal(openWin.precision, "f16-bits");
  assert.deepEqual(Array.from(openWin.halfBits!), Array.from(full.halfBits!));
  assert.deepEqual(Array.from(exactWin.halfBits!), Array.from(full.halfBits!));
  free_deep(deep.handle);
});

test("flatten_deep far cutoff (window ending mid-Z) yields ONLY the front", async () => {
  const { open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  const full = flatten_deep(deep.handle, -Infinity, Infinity); // both samples
  const clip = flatten_deep(deep.handle, -Infinity, 7); // drops back (Z=10); keeps front (Z=1) + single (Z=5)
  const fh = full.halfBits!;
  const ch = clip.halfBits!;

  let twoCount = 0;
  let oneCount = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const i = (y * W + x) * 4;
      const aFull = h2f(fh[i + 3]!);
      const aClip = h2f(ch[i + 3]!);
      if (twoSample(x, y)) {
        twoCount++;
        // Full composites front(a=0.5) OVER back(a=1) → total alpha 1.0; the
        // Z=7 cut keeps only the semi-transparent front → alpha 0.5.
        assert.ok(Math.abs(aFull - 1.0) < 1e-3, `full alpha≈1 at (${x},${y}), got ${aFull}`);
        assert.ok(Math.abs(aClip - 0.5) < 1e-3, `clip alpha≈0.5 at (${x},${y}), got ${aClip}`);
      } else {
        oneCount++;
        // Single sample at Z=5 (≤ 7) is in BOTH composites → identical bits.
        for (let c = 0; c < 4; c++) {
          assert.equal(ch[i + c], fh[i + c], `single-sample pixel (${x},${y}) ch ${c} differs`);
        }
      }
    }
  }
  assert.ok(twoCount > 0 && oneCount > 0, "fixture must have both pixel kinds");
  free_deep(deep.handle);
});

test("evicted (over-budget → redecode) handle flattens identically to retained", async () => {
  const { decode_exr, open_deep, flatten_deep, free_deep, set_deep_budget } =
    await loadExrDecoder();
  const full = decode_exr(fixture("deep-rgba-32x32.exr"));
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  try {
    // Force the global LRU budget to 0 → every retained handle (incl. this one)
    // is evicted to redecode-from-cached-bytes mode. Correctness must not change.
    set_deep_budget(0);
    const flat = flatten_deep(deep.handle, -Infinity, Infinity);
    assert.deepEqual(Array.from(flat.halfBits!), Array.from(full.halfBits!));
    // A mid-Z far cut still yields only the front (α 0.5) on 2-sample pixels.
    const clip = flatten_deep(deep.handle, -Infinity, 7);
    const ch = clip.halfBits!;
    let checked = 0;
    for (let y = 0; y < H; y++) {
      for (let x = 0; x < W; x++) {
        if (!twoSample(x, y)) continue;
        checked++;
        assert.ok(Math.abs(h2f(ch[(y * W + x) * 4 + 3]!) - 0.5) < 1e-3);
      }
    }
    assert.ok(checked > 0);
  } finally {
    free_deep(deep.handle);
    set_deep_budget(512 * 1024 * 1024); // restore default for other tests
  }
});

test("flatten_deep window EXCLUDING the front composites only the back", async () => {
  const { open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  // Window [8, +inf): drops the front (Z=1) AND the single (Z=5); keeps only the
  // back (Z=10, opaque) on 2-sample pixels.
  const back = flatten_deep(deep.handle, 8, Infinity);
  const front = flatten_deep(deep.handle, -Infinity, 7); // front (+ single) only
  const bh = back.halfBits!;
  const fh = front.halfBits!;
  let two = 0;
  let one = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const i = (y * W + x) * 4;
      if (twoSample(x, y)) {
        two++;
        // Back sample is opaque → alpha 1.0; and it DIFFERS from the front-only
        // window (alpha 0.5), so the near cutoff genuinely dropped the front.
        assert.ok(Math.abs(h2f(bh[i + 3]!) - 1.0) < 1e-3, `back-only α≈1 at (${x},${y})`);
        assert.ok(Math.abs(h2f(fh[i + 3]!) - 0.5) < 1e-3, `front-only α≈0.5 at (${x},${y})`);
      } else {
        one++;
        // Single sample sits at Z=5 (< 8) → excluded by [8,∞) → fully empty.
        assert.equal(h2f(bh[i + 3]!), 0, `single pixel (${x},${y}) excluded → α 0`);
      }
    }
  }
  assert.ok(two > 0 && one > 0);
  free_deep(deep.handle);
});

test("deep_z_range_in_rect reports the Z range of samples in an image rect", async () => {
  const { open_deep, deep_z_range_in_rect, free_deep } = await loadExrDecoder();
  const deep = open_deep(fixture("deep-rgba-32x32.exr"))!;
  // Full frame → the whole volume [zMin, zMax] = [1, 10], every sample counted.
  const full = deep_z_range_in_rect(deep.handle, 0, 0, W - 1, H - 1);
  assert.equal(full.zMin, 1);
  assert.equal(full.zMax, 10);
  assert.equal(full.count, deep.totalSamples);
  // A single 2-sample pixel (0,0): samples at Z=1 and Z=10.
  const two = deep_z_range_in_rect(deep.handle, 0, 0, 0, 0);
  assert.equal(two.zMin, 1);
  assert.equal(two.zMax, 10);
  assert.equal(two.count, 2);
  // A single 1-sample pixel (1,0) (Z=5): a degenerate [5,5] range.
  const one = deep_z_range_in_rect(deep.handle, 1, 0, 1, 0);
  assert.equal(one.zMin, 5);
  assert.equal(one.zMax, 5);
  assert.equal(one.count, 1);
  free_deep(deep.handle);
});

test("deep_z_range_in_rect reports count 0 for an empty region (a VALID selection)", async () => {
  const { open_deep, deep_z_range_in_rect, free_deep } = await loadExrDecoder();
  // deep-holes-8x8: left half (x<4) has 1 sample at Z=3; right half is empty.
  const deep = open_deep(fixture("deep-holes-8x8.exr"))!;
  const left = deep_z_range_in_rect(deep.handle, 0, 0, 3, 7);
  assert.equal(left.zMin, 3);
  assert.equal(left.zMax, 3);
  assert.equal(left.count, 32); // 4 columns × 8 rows
  const right = deep_z_range_in_rect(deep.handle, 4, 0, 7, 7);
  assert.equal(right.count, 0); // empty region — the host maps this to an empty window
  free_deep(deep.handle);
});

test("an empty (crossed zNear > zFar) window composites fully transparent", async () => {
  const { open_deep, flatten_deep, free_deep } = await loadExrDecoder();
  // deep-holes-8x8 is a SINGLE-Z image (all samples at Z=3, so zMin==zMax==3):
  // the host's empty sentinel there is the strictly-crossed [zMax+1, zMin-1] =
  // [4, 2]. Must render nothing (every half is 0 = transparent black).
  const deep = open_deep(fixture("deep-holes-8x8.exr"))!;
  assert.equal(deep.zMin, 3);
  assert.equal(deep.zMax, 3);
  const empty = flatten_deep(deep.handle, 4, 2); // crossed ⇒ empty
  const eh = empty.halfBits!;
  assert.ok(
    eh.every((v) => v === 0),
    "crossed window on a single-Z image → fully transparent",
  );
  // A NON-empty window at Z=3 DOES show the left-half content (a sanity anchor).
  const full = flatten_deep(deep.handle, -Infinity, Infinity);
  const fh = full.halfBits!;
  assert.ok(fh.some((v) => v !== 0), "full composite shows the populated pixels");
  free_deep(deep.handle);

  // And on the multi-Z fixture, any crossed window is transparent too.
  const deep2 = open_deep(fixture("deep-rgba-32x32.exr"))!;
  const empty2 = flatten_deep(deep2.handle, deep2.zMax, deep2.zMin); // [10, 1] crossed
  assert.ok(empty2.halfBits!.every((v) => v === 0), "crossed window on multi-Z → transparent");
  free_deep(deep2.handle);
});
