/**
 * Coverage tests for the OpenEXR-wasm decoder (the format pivot): every EXR
 * shape the retired Rust `exr`-crate wasm and the pure-TS decoder REJECTED now
 * decodes through the inline module. Fixtures are synthetically generated by
 * wasm/openexr/fixtures/gen.cpp (OpenEXR v3.4.9), committed <200KB crops.
 *
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/image/decoders/exr-openexr-coverage.test.ts
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { loadExrDecoder } from "./wasm-inline/wasm-exr-inline.ts";

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));
}

// ZIP half + tiled ZIP half encode the same wave() image losslessly, so the
// flat-scanline and flat-tiled read paths must agree bit-for-bit.
test("ZIP half (scanline) and ZIP half (tiled) decode identically", async () => {
  const { decode_exr } = await loadExrDecoder();
  const flat = decode_exr(fixture("rgb-zip-half-64x48.exr"));
  const tiled = decode_exr(fixture("tiled-zip-half-64x48.exr"));
  assert.equal(flat.precision, "f16-bits");
  assert.equal(tiled.precision, "f16-bits");
  assert.equal(tiled.width, 64);
  assert.equal(tiled.height, 48);
  assert.equal(tiled.channels, 3);
  assert.deepEqual(Array.from(tiled.halfBits!), Array.from(flat.halfBits!));
});

// HTJ2K (OpenEXR 3.4 + OpenJPH) — the headline of the pivot. Lossless HTJ2K of
// the same source reproduces the ZIP half bits exactly.
test("HTJ2K half decodes bit-exact to the ZIP half reference", async () => {
  const { decode_exr } = await loadExrDecoder();
  const zip = decode_exr(fixture("rgb-zip-half-64x48.exr"));
  const htj2k = decode_exr(fixture("htj2k-half-64x48.exr"));
  assert.equal(htj2k.precision, "f16-bits");
  assert.equal(htj2k.channels, 3);
  assert.deepEqual(Array.from(htj2k.halfBits!), Array.from(zip.halfBits!));
});

// Luminance-chroma (Y/RY/BY) — RgbaInputFile does the YC→RGBA reconstruction
// natively; output stays HALF.
test("luminance-chroma reconstructs to HALF RGB", async () => {
  const { decode_exr } = await loadExrDecoder();
  const img = decode_exr(fixture("luma-chroma-64x48.exr"));
  assert.equal(img.width, 64);
  assert.equal(img.height, 48);
  assert.equal(img.channels, 3); // no alpha channel in the source
  assert.equal(img.precision, "f16-bits");
  assert.ok(img.halfBits instanceof Uint16Array);
  assert.equal(img.halfBits!.length, 64 * 48 * 3);
});

// PIZ FLOAT → the f32 output path (not all-HALF).
test("PIZ float decodes to f32 (non-half output path)", async () => {
  const { decode_exr } = await loadExrDecoder();
  const img = decode_exr(fixture("rgb-piz-float-64x48.exr"));
  assert.equal(img.precision, "f32");
  assert.equal(img.channels, 3);
  assert.ok(img.floats instanceof Float32Array);
  assert.equal(img.halfBits, undefined);
  assert.equal(img.floats!.length, 64 * 48 * 3);
});

// Deep scanline RGBA → per-pixel Z-sorted OVER flatten to premultiplied RGBA
// HALF. The front sample (smaller Z) is written SECOND in the file, so a correct
// decoder must sort by Z, not by file order.
test("deep RGBA flattens to premultiplied RGBA HALF (Z-sorted OVER)", async () => {
  const { decode_exr } = await loadExrDecoder();
  const img = decode_exr(fixture("deep-rgba-32x32.exr"));
  assert.equal(img.width, 32);
  assert.equal(img.height, 32);
  assert.equal(img.channels, 4); // RGBA
  assert.equal(img.precision, "f16-bits");
  assert.equal(img.halfBits!.length, 32 * 32 * 4);
  // Every composited alpha is finite and within [0,1] (premultiplied OVER).
  const half = img.halfBits!;
  const h2f = (b: number) => {
    const s = (b & 0x8000) >> 15, e = (b & 0x7c00) >> 10, f = b & 0x03ff;
    let v: number;
    if (e === 0) v = (f / 1024) * 2 ** -14;
    else if (e === 0x1f) v = f ? NaN : Infinity;
    else v = (1 + f / 1024) * 2 ** (e - 15);
    return s ? -v : v;
  };
  for (let i = 0; i < 32 * 32; i++) {
    const a = h2f(half[i * 4 + 3]!);
    assert.ok(a >= 0 && a <= 1.0001, `alpha in range at ${i}: ${a}`);
  }
});
