/**
 * CPU TS reference implementation of LDR-FLIP (Andersson et al. 2020,
 * "FLIP: A Difference Evaluator for Alternating Images").
 *
 * This is a plain-loops, small-image-scale port of the canonical NVIDIA FLIP
 * reference algorithm (full-2D CSF filters). It is the reference of truth the
 * GPU multi-pass kernel (`flip.wgsl.ts`) is verified against in the browser
 * harness (`engine/__tests__/flip.browser.ts`), and is itself verified in a
 * node test (`flip-reference.test.ts`) against expected values generated by
 * the official `flip-evaluator` package — see that test + the committed
 * fixtures (`__fixtures__/flip-ldr.json`) for provenance.
 *
 * Verified: this port matches `flip-evaluator==1.7` (compiled NVIDIA FLIP,
 * LDR mode, inputsRGB, ppd=67) to a worst-case per-pixel abs difference of
 * ~8.4e-5 across the committed fixture pairs (typically ~1e-6) — i.e. it is a
 * faithful, not approximate, reimplementation.
 *
 * ## Pipeline (per the paper / reference)
 *   1. sRGB -> linear RGB -> XYZ (D65) -> YCxCz.
 *   2. Per-channel CSF spatial filtering (Y=S_A, Cx=S_RG, Cz=S_BY), each a
 *      normalized sum-of-Gaussians 2D filter, radius from ppd.
 *   3. filtered YCxCz -> linear RGB -> clamp[0,1] -> XYZ -> CIELAB -> Hunt.
 *   4. color difference: HyAB in Hunt-adjusted L*a*b*, power `qc`, redistributed
 *      about `pc*cmax` to `pt`.
 *   5. feature difference: 1st/2nd Gaussian-derivative edge/point filters on the
 *      (unfiltered) achromatic channel, power `qf`.
 *   6. flip = deltaE_c ^ (1 - deltaE_f).
 */

// linear RGB -> XYZ (D65) — exact rationals from FLIP.h.
const M_RGB2XYZ = [
  [10135552 / 24577794, 8788810 / 24577794, 4435075 / 24577794],
  [2613072 / 12288897, 8788810 / 12288897, 887015 / 12288897],
  [1425312 / 73733382, 8788810 / 73733382, 70074185 / 73733382],
];
// XYZ -> linear RGB (inverse of the above).
const M_XYZ2RGB = invert3(M_RGB2XYZ);
// Inverse D65 white used to normalize XYZ before YCxCz / CIELAB.
const WHITE_INV: [number, number, number] = [1.052156925, 1.0, 0.918357670];

// FLIP constants (paper / reference).
const QC = 0.7; // color-difference exponent
const QF = 0.5; // feature-difference exponent
const PC = 0.4; // redistribution anchor (fraction of cmax)
const PT = 0.95; // redistribution target
const GW = 0.082; // feature-filter width coefficient

function invert3(m: number[][]): number[][] {
  const [a, b, c] = m[0]!;
  const [d, e, f] = m[1]!;
  const [g, h, i] = m[2]!;
  const A = e! * i! - f! * h!;
  const B = -(d! * i! - f! * g!);
  const C = d! * h! - e! * g!;
  const det = a! * A + b! * B + c! * C;
  const inv = 1 / det;
  return [
    [A * inv, -(b! * i! - c! * h!) * inv, (b! * f! - c! * e!) * inv],
    [B * inv, (a! * i! - c! * g!) * inv, -(a! * f! - c! * d!) * inv],
    [C * inv, -(a! * h! - b! * g!) * inv, (a! * e! - b! * d!) * inv],
  ];
}

function srgb2linear(c: number): number {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function mat3mul(m: number[][], x: number, y: number, z: number): [number, number, number] {
  return [
    m[0]![0]! * x + m[0]![1]! * y + m[0]![2]! * z,
    m[1]![0]! * x + m[1]![1]! * y + m[1]![2]! * z,
    m[2]![0]! * x + m[2]![1]! * y + m[2]![2]! * z,
  ];
}

function xyz2ycxcz(x: number, y: number, z: number): [number, number, number] {
  const nx = x * WHITE_INV[0];
  const ny = y * WHITE_INV[1];
  const nz = z * WHITE_INV[2];
  return [116 * ny - 16, 500 * (nx - ny), 200 * (ny - nz)];
}

function ycxcz2linrgb(Y: number, Cx: number, Cz: number): [number, number, number] {
  const yy = (Y + 16) / 116;
  const x = (yy + Cx / 500) / WHITE_INV[0];
  const yN = yy / WHITE_INV[1];
  const z = (yy - Cz / 200) / WHITE_INV[2];
  return mat3mul(M_XYZ2RGB, x, yN, z);
}

const LAB_DELTA = 6 / 29;
function labF(t: number): number {
  return t > LAB_DELTA ** 3 ? Math.cbrt(t) : t / (3 * LAB_DELTA * LAB_DELTA) + 4 / 29;
}

/** linear RGB (clamped [0,1]) -> Hunt-adjusted CIELAB. */
function linrgb2huntLab(r: number, g: number, b: number): [number, number, number] {
  const [x, y, z] = mat3mul(M_RGB2XYZ, r, g, b);
  const fx = labF(x * WHITE_INV[0]);
  const fy = labF(y * WHITE_INV[1]);
  const fz = labF(z * WHITE_INV[2]);
  const L = 116 * fy - 16;
  const a = 500 * (fx - fy);
  const bb = 200 * (fy - fz);
  // Hunt adjustment: a,b scaled by 0.01*L.
  return [L, 0.01 * L * a, 0.01 * L * bb];
}

function hyab(l1: [number, number, number], l2: [number, number, number]): number {
  const dL = l1[0] - l2[0];
  const da = l1[1] - l2[1];
  const db = l1[2] - l2[2];
  return Math.abs(dL) + Math.sqrt(da * da + db * db);
}

/** cmax = HyAB(green, blue) ^ qc, greens/blues run through the color pipeline. */
function computeCmax(): number {
  const green = linrgb2huntLab(0, 1, 0);
  const blue = linrgb2huntLab(0, 0, 1);
  return Math.pow(hyab(green, blue), QC);
}
const CMAX = computeCmax();

interface Filter {
  weights: Float64Array; // (2r+1)^2, row-major
  r: number;
}

/** Per-channel CSF filters [S_A, S_RG, S_BY], normalized to sum 1. */
function csfFilters(ppd: number): [Filter, Filter, Filter] {
  const a1 = [1.0, 1.0, 34.1];
  const b1 = [0.0047, 0.0053, 0.04];
  const a2 = [0.0, 0.0, 13.5];
  const b2 = [1e-5, 1e-5, 0.025];
  const maxScale = Math.max(...b1, ...b2);
  const r = Math.ceil(3 * Math.sqrt(maxScale / (2 * Math.PI ** 2)) * ppd);
  const deltaX = 1 / ppd;
  const n = 2 * r + 1;
  const out: Filter[] = [];
  for (let c = 0; c < 3; c++) {
    const w = new Float64Array(n * n);
    let sum = 0;
    for (let y = -r, k = 0; y <= r; y++) {
      for (let x = -r; x <= r; x++, k++) {
        const z = (x * deltaX) ** 2 + (y * deltaX) ** 2;
        const pi2 = Math.PI ** 2;
        const g =
          a1[c]! * Math.sqrt(Math.PI / b1[c]!) * Math.exp((-pi2 * z) / b1[c]!) +
          a2[c]! * Math.sqrt(Math.PI / b2[c]!) * Math.exp((-pi2 * z) / b2[c]!);
        w[k] = g;
        sum += g;
      }
    }
    for (let i = 0; i < w.length; i++) w[i] = w[i]! / sum;
    out.push({ weights: w, r });
  }
  return out as [Filter, Filter, Filter];
}

/** Edge (1st-deriv) + point (2nd-deriv) feature filters, pos/neg normalized to +/-1. */
function featureFilters(ppd: number): { edge: Filter; point: Filter } {
  const sd = 0.5 * GW * ppd;
  const r = Math.ceil(3 * sd);
  const n = 2 * r + 1;
  const edge = new Float64Array(n * n);
  const point = new Float64Array(n * n);
  let edgePos = 0,
    edgeNeg = 0,
    pointPos = 0,
    pointNeg = 0;
  for (let y = -r, k = 0; y <= r; y++) {
    for (let x = -r; x <= r; x++, k++) {
      const g = Math.exp(-(x * x + y * y) / (2 * sd * sd));
      const e = -x * g;
      const p = ((x * x) / (sd * sd) - 1) * g;
      edge[k] = e;
      point[k] = p;
      if (e > 0) edgePos += e;
      else edgeNeg -= e;
      if (p > 0) pointPos += p;
      else pointNeg -= p;
    }
  }
  for (let i = 0; i < edge.length; i++) {
    edge[i] = edge[i]! > 0 ? edge[i]! / edgePos : edge[i]! / edgeNeg;
    point[i] = point[i]! > 0 ? point[i]! / pointPos : point[i]! / pointNeg;
  }
  return { edge: { weights: edge, r }, point: { weights: point, r } };
}

/** Reflect-to-edge (replicate) clamp. */
function clampIdx(v: number, hi: number): number {
  return v < 0 ? 0 : v > hi ? hi : v;
}

/** 2D convolution of a single-channel W*H plane with a filter, edge-clamped. */
function convolve(plane: Float64Array, W: number, H: number, f: Filter): Float64Array {
  const out = new Float64Array(W * H);
  const r = f.r;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      let acc = 0;
      for (let dy = -r, ki = 0; dy <= r; dy++) {
        const sy = clampIdx(y + dy, H - 1);
        for (let dx = -r; dx <= r; dx++, ki++) {
          const sx = clampIdx(x + dx, W - 1);
          acc += f.weights[ki]! * plane[sy * W + sx]!;
        }
      }
      out[y * W + x] = acc;
    }
  }
  return out;
}

// Transposed convolution (swap the filter's x/y — for the y-direction feature
// filters). The feature filter is `edge`/`point` built as a derivative in x; the
// y-direction filter is its transpose.
function convolveT(plane: Float64Array, W: number, H: number, f: Filter): Float64Array {
  const r = f.r;
  const n = 2 * r + 1;
  const tw = new Float64Array(f.weights.length);
  for (let a = 0; a < n; a++) for (let b = 0; b < n; b++) tw[a * n + b] = f.weights[b * n + a]!;
  return convolve(plane, W, H, { weights: tw, r });
}

/**
 * Compute the LDR-FLIP error map. `refSRGB`/`testSRGB` are length `W*H*3`
 * (interleaved RGB, no alpha), values in [0,1] sRGB. Returns a length `W*H`
 * Float32Array of FLIP error in [0,1].
 */
export function flipLDR(
  refSRGB: ArrayLike<number>,
  testSRGB: ArrayLike<number>,
  W: number,
  H: number,
  ppd = 67,
): Float32Array {
  const N = W * H;
  // Stage 1: sRGB -> YCxCz for both images.
  const refYc = [new Float64Array(N), new Float64Array(N), new Float64Array(N)];
  const testYc = [new Float64Array(N), new Float64Array(N), new Float64Array(N)];
  for (let i = 0; i < N; i++) {
    for (const [src, dst] of [
      [refSRGB, refYc],
      [testSRGB, testYc],
    ] as const) {
      const r = srgb2linear(src[i * 3]!);
      const g = srgb2linear(src[i * 3 + 1]!);
      const b = srgb2linear(src[i * 3 + 2]!);
      const [x, y, z] = mat3mul(M_RGB2XYZ, r, g, b);
      const [Y, Cx, Cz] = xyz2ycxcz(x, y, z);
      dst[0]![i] = Y;
      dst[1]![i] = Cx;
      dst[2]![i] = Cz;
    }
  }

  // Stage 2: CSF filtering per channel, then -> Hunt-Lab.
  const csf = csfFilters(ppd);
  const toLab = (yc: Float64Array[]): [Float64Array, Float64Array, Float64Array] => {
    const fY = convolve(yc[0]!, W, H, csf[0]);
    const fCx = convolve(yc[1]!, W, H, csf[1]);
    const fCz = convolve(yc[2]!, W, H, csf[2]);
    const L = new Float64Array(N);
    const A = new Float64Array(N);
    const B = new Float64Array(N);
    for (let i = 0; i < N; i++) {
      let [r, g, b] = ycxcz2linrgb(fY[i]!, fCx[i]!, fCz[i]!);
      r = Math.min(1, Math.max(0, r));
      g = Math.min(1, Math.max(0, g));
      b = Math.min(1, Math.max(0, b));
      const lab = linrgb2huntLab(r, g, b);
      L[i] = lab[0];
      A[i] = lab[1];
      B[i] = lab[2];
    }
    return [L, A, B];
  };
  const [rL, rA, rB] = toLab(refYc);
  const [tL, tA, tB] = toLab(testYc);

  // Stage 3: color difference (HyAB) + redistribution.
  const pccmax = PC * CMAX;
  const deltaEc = new Float64Array(N);
  for (let i = 0; i < N; i++) {
    const hd = hyab([rL[i]!, rA[i]!, rB[i]!], [tL[i]!, tA[i]!, tB[i]!]);
    const power = Math.pow(hd, QC);
    deltaEc[i] =
      power < pccmax
        ? (PT / pccmax) * power
        : PT + ((power - pccmax) / (CMAX - pccmax)) * (1 - PT);
  }

  // Stage 4: feature difference on the (unfiltered) achromatic channel.
  const feat = featureFilters(ppd);
  const refY01 = new Float64Array(N);
  const testY01 = new Float64Array(N);
  for (let i = 0; i < N; i++) {
    refY01[i] = (refYc[0]![i]! + 16) / 116;
    testY01[i] = (testYc[0]![i]! + 16) / 116;
  }
  const feats = (y: Float64Array) => {
    const ex = convolve(y, W, H, feat.edge);
    const ey = convolveT(y, W, H, feat.edge);
    const px = convolve(y, W, H, feat.point);
    const py = convolveT(y, W, H, feat.point);
    const edges = new Float64Array(N);
    const points = new Float64Array(N);
    for (let i = 0; i < N; i++) {
      edges[i] = Math.hypot(ex[i]!, ey[i]!);
      points[i] = Math.hypot(px[i]!, py[i]!);
    }
    return { edges, points };
  };
  const rf = feats(refY01);
  const tf = feats(testY01);

  // Stage 5: combine.
  const out = new Float32Array(N);
  const invSqrt2 = 1 / Math.sqrt(2);
  for (let i = 0; i < N; i++) {
    const df = Math.max(Math.abs(rf.edges[i]! - tf.edges[i]!), Math.abs(rf.points[i]! - tf.points[i]!));
    const deltaEf = Math.pow(invSqrt2 * df, QF);
    out[i] = Math.pow(deltaEc[i]!, 1 - deltaEf);
  }
  return out;
}

/** The cmax constant (exposed for the GPU kernel, which needs it as a uniform). */
export const FLIP_CMAX = CMAX;
