/**
 * Node test: the CPU LDR-FLIP reference (`flip-reference.ts`) vs
 * officially-generated expected values.
 *
 * Run:
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/engine/kernels/flip-reference.test.ts
 *
 * ## Provenance of the expected values (`__fixtures__/flip-ldr.json`)
 * The fixtures' `expectedFlip` maps + `expectedMean` were generated by the
 * OFFICIAL NVIDIA FLIP implementation, distributed as the `flip-evaluator`
 * pip package (v1.7, the compiled `nbflip.abi3.so`), invoked as
 * `flip_evaluator.evaluate(ref, test, "LDR", inputsRGB=True, applyMagma=False,
 * parameters={"ppd": 67})`. The generator script is committed in the PR
 * description / scratch (`gen_fixtures.py`); it also cross-checked a standalone
 * numpy port (from which `flip-reference.ts` is transcribed) against the .so to
 * a worst-case per-pixel abs diff of ~8.4e-5. The fixtures are committed +
 * fully offline; this test needs no network and no GPU.
 *
 * This is the FIRST of the two-sided FLIP verification (spec §FLIP): here the
 * CPU reference is checked against the official values; the browser harness
 * (`engine/__tests__/flip.browser.ts`) checks the GPU kernel against this CPU
 * reference.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { flipLDR } from "./flip-reference.ts";

const here = dirname(fileURLToPath(import.meta.url));
interface Fixture {
  provenance: string;
  ppd: number;
  cases: {
    name: string;
    width: number;
    height: number;
    refSRGB: number[];
    testSRGB: number[];
    expectedFlip: number[];
    expectedMean: number;
  }[];
}
const fx: Fixture = JSON.parse(readFileSync(join(here, "__fixtures__", "flip-ldr.json"), "utf8"));

// The CPU reference is a faithful (not approximate) transcription of the
// official algorithm; the small residual vs the compiled .so is float
// precision + the C++/CUDA separated-filter approximation. Empirically the
// worst per-pixel residual over these fixtures is ~1e-4, so 5e-4 is a safe,
// still-meaningful bound.
const PIXEL_TOL = 5e-4;
const MEAN_TOL = 1e-4;

for (const c of fx.cases) {
  test(`FLIP CPU reference matches official flip-evaluator: ${c.name}`, () => {
    const got = flipLDR(c.refSRGB, c.testSRGB, c.width, c.height, fx.ppd);
    assert.equal(got.length, c.width * c.height, "output length");
    let worst = 0;
    let sum = 0;
    for (let i = 0; i < got.length; i++) {
      const d = Math.abs(got[i]! - c.expectedFlip[i]!);
      if (d > worst) worst = d;
      sum += got[i]!;
    }
    assert.ok(worst <= PIXEL_TOL, `${c.name}: worst per-pixel diff ${worst} > ${PIXEL_TOL}`);
    const mean = sum / got.length;
    assert.ok(
      Math.abs(mean - c.expectedMean) <= MEAN_TOL,
      `${c.name}: mean ${mean} vs official ${c.expectedMean}`,
    );
  });
}

test("FLIP of identical images is ~0", () => {
  const n = 6 * 6 * 3;
  const img = new Float32Array(n);
  for (let i = 0; i < n; i++) img[i] = (i % 7) / 7;
  const out = flipLDR(img, img, 6, 6, 67);
  for (const v of out) assert.ok(v < 1e-6, `identical -> ${v}`);
});
