/**
 * CPU TS reference implementation of HDR-FLIP (Andersson et al. 2021,
 * "Visualizing Errors in Rendered High Dynamic Range Images", Eurographics).
 *
 * Faithful, plain-loops port of the official NVIDIA FLIP HDR algorithm
 * (transcribed from the reference `src/pytorch/flip_loss.py`: `HDRFLIPLoss`,
 * `tone_map`, `compute_start_stop_exposures`). It is the reference of truth the
 * GPU multi-pass kernel (`hdr-flip.ts`) is verified against in the browser
 * harness (`engine/__tests__/hdr-flip.browser.ts`), and is itself verified in a
 * node test (`hdr-flip-reference.test.ts`) against expected values generated by
 * the official compiled `flip-evaluator` package (HDR mode) — see that test +
 * the committed fixtures (`__fixtures__/flip-hdr.json`) for provenance.
 *
 * ## Algorithm (per the paper / reference)
 *   1. Automatic exposure range from the REFERENCE image's linear luminance:
 *        Y = 0.2126 R + 0.7152 G + 0.0722 B  (linear)
 *        x_* solves the (default ACES) tone mapper t(x)=tmax/tmin at t=0.85.
 *        c_start = log2(x_max / max(Y));  c_stop = log2(x_min / median(Y)).
 *      (Overridable via `startExposure`/`stopExposure`.)
 *   2. num_exposures = max(2, ceil(c_stop - c_start));
 *      step = (c_stop - c_start) / max(num_exposures - 1, 1).
 *   3. For each exposure c_i: exposure-compensate (x = 2^c_i · linRGB), apply
 *      the tone mapper, treat the tone-mapped (linear) result as linear RGB →
 *      YCxCz, run the shared LDR-FLIP core (`flipCoreFromYCxCz`).
 *   4. HDR-FLIP = per-pixel MAXIMUM of the LDR-FLIP maps over all exposures.
 *
 * Only the ACES tone mapper is implemented (the default + the only one the
 * kernel/pane surface); the reference's Hable/Reinhard branches are omitted.
 */
import { flipCoreFromYCxCz, linrgb2ycxcz, type YCxCzPlanes } from "./flip-reference.ts";

// ACES filmic tone-mapper rational-polynomial coefficients, with pre-exposure
// cancellation folded in (verbatim from flip_loss.py `tone_map`/
// `compute_start_stop_exposures`, ACES branch).
const K0 = 0.6 * 0.6 * 2.51;
const K1 = 0.6 * 0.03;
const K2 = 0;
const K3 = 0.6 * 0.6 * 2.43;
const K4 = 0.6 * 0.59;
const K5 = 0.14;

/** ACES tone map of a single (already exposure-compensated) linear channel. */
function acesToneMapChannel(x: number): number {
  const x2 = x * x;
  const nom = K0 * x2 + K1 * x + K2;
  const denom = K3 * x2 + K4 * x + K5;
  const y = denom === 0 || !Number.isFinite(denom) ? 1 : nom / denom;
  return Math.min(1, Math.max(0, y));
}

/** Solve ACES t(x) = t for x (the positive root), per `compute_start_stop_exposures`. */
function acesInverse(t: number): number {
  const c0 = (K1 - K4 * t) / (K0 - K3 * t);
  const c1 = (K2 - K5 * t) / (K0 - K3 * t);
  return -0.5 * c0 + Math.sqrt((0.5 * c0) ** 2 - c1);
}

const TMAX = 0.85; // t value used for the start exposure (from reference max luminance)
const TMIN = 0.85; // t value used for the stop exposure (from reference median luminance)
const FLT_EPS = 1.1920928955078125e-7; // np.finfo(float32).eps — median clamp

const LUM = [0.2126, 0.7152, 0.0722] as const;

/** Read the RGB of pixel `i` from an interleaved `channels`-wide array (1→gray). */
function readRGB(data: ArrayLike<number>, i: number, channels: number): [number, number, number] {
  const b = i * channels;
  if (channels === 1) {
    const v = data[b]!;
    return [v, v, v];
  }
  return [data[b]!, data[b + 1]!, data[b + 2]!];
}

export interface HdrExposureParams {
  startExposure: number;
  stopExposure: number;
  numExposures: number;
}

export interface HdrFlipOptions {
  /** Explicit start exposure (c_start) override; skips the max-luminance step. */
  startExposure?: number;
  /** Explicit stop exposure (c_stop) override; skips the median-luminance step. */
  stopExposure?: number;
}

/**
 * Compute the automatic (or overridden) HDR-FLIP exposure range + count from a
 * REFERENCE linear-RGB image. DETERMINISTIC per source content (max + median of
 * luminance), so its outputs are safe to fold into the diff-cache params hash.
 * `channels` is the interleave width of `refLinRGB` (1/3/4).
 */
export function computeHdrFlipExposures(
  refLinRGB: ArrayLike<number>,
  W: number,
  H: number,
  channels = 3,
  opts: HdrFlipOptions = {},
): HdrExposureParams {
  const N = W * H;
  const xMax = acesInverse(TMAX);
  const xMin = acesInverse(TMIN);

  // Luminance of the reference (linear).
  const Y = new Float64Array(N);
  let yHi = 0;
  for (let i = 0; i < N; i++) {
    const [r, g, b] = readRGB(refLinRGB, i, channels);
    const y = r * LUM[0] + g * LUM[1] + b * LUM[2];
    Y[i] = y;
    if (y > yHi) yHi = y;
  }
  // Median luminance (clamped to FLT_EPS, matching the reference).
  const sorted = Float64Array.from(Y).sort();
  const mid = N >> 1;
  const median = N % 2 === 1 ? sorted[mid]! : sorted[mid - 1]!; // torch.median: lower-mid for even N
  const yLo = Math.max(median, FLT_EPS);
  // Guard a fully-black reference (yHi=0) so log2 stays finite.
  const yHiSafe = Math.max(yHi, FLT_EPS);

  const startExposure = opts.startExposure ?? Math.log2(xMax / yHiSafe);
  const stopExposure = opts.stopExposure ?? Math.log2(xMin / yLo);
  const numExposures = Math.max(2, Math.ceil(stopExposure - startExposure));
  return { startExposure, stopExposure, numExposures };
}

/**
 * Compute the HDR-FLIP error map. `refLinRGB`/`testLinRGB` are length `W*H*3`
 * (interleaved linear-sRGB RGB, nonnegative). Returns a length `W*H`
 * Float32Array of HDR-FLIP error in [0,1].
 */
export function flipHDR(
  refLinRGB: ArrayLike<number>,
  testLinRGB: ArrayLike<number>,
  W: number,
  H: number,
  ppd = 67,
  opts: HdrFlipOptions = {},
): Float32Array {
  const N = W * H;
  const { startExposure, stopExposure, numExposures } = computeHdrFlipExposures(
    refLinRGB,
    W,
    H,
    3,
    opts,
  );
  const stepSize = (stopExposure - startExposure) / Math.max(numExposures - 1, 1);

  const out = new Float32Array(N); // starts at 0 — the per-pixel running max
  const refYc: YCxCzPlanes = [new Float64Array(N), new Float64Array(N), new Float64Array(N)];
  const testYc: YCxCzPlanes = [new Float64Array(N), new Float64Array(N), new Float64Array(N)];

  for (let e = 0; e < numExposures; e++) {
    const exposure = startExposure + e * stepSize;
    const scale = 2 ** exposure;
    for (let i = 0; i < N; i++) {
      const [rr, rg, rb] = readRGB(refLinRGB, i, 3);
      const [tr, tg, tb] = readRGB(testLinRGB, i, 3);
      const [ry, rcx, rcz] = linrgb2ycxcz(
        acesToneMapChannel(scale * rr),
        acesToneMapChannel(scale * rg),
        acesToneMapChannel(scale * rb),
      );
      const [ty, tcx, tcz] = linrgb2ycxcz(
        acesToneMapChannel(scale * tr),
        acesToneMapChannel(scale * tg),
        acesToneMapChannel(scale * tb),
      );
      refYc[0][i] = ry;
      refYc[1][i] = rcx;
      refYc[2][i] = rcz;
      testYc[0][i] = ty;
      testYc[1][i] = tcx;
      testYc[2][i] = tcz;
    }
    const flipE = flipCoreFromYCxCz(refYc, testYc, W, H, ppd);
    for (let i = 0; i < N; i++) if (flipE[i]! > out[i]!) out[i] = flipE[i]!;
  }
  return out;
}
