/**
 * Node test: the CPU HDR-FLIP reference (`hdr-flip-reference.ts`) vs
 * officially-generated expected values.
 *
 * Run:
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/engine/kernels/hdr-flip-reference.test.ts
 *
 * ## Provenance of the expected values (`__fixtures__/flip-hdr.json`)
 * The fixtures' `expectedFlip` maps + `expectedMean` were generated by the
 * OFFICIAL NVIDIA FLIP implementation, distributed as the `flip-evaluator` pip
 * package (compiled `nbflip.abi3.so`), invoked in HDR mode as
 * `flip_evaluator.evaluate(ref, test, "HDR", inputsRGB=False, applyMagma=False,
 * parameters={"ppd": 67})` — default ACES tone mapper, automatic exposure range.
 * The reference/test images are small synthetic linear-sRGB float HDR pairs (a
 * dim background with a bright gaussian core + a highlight-localized test error;
 * one case is a very-dark-background / very-bright-core "wide" pair that yields a
 * wide auto exposure range, i.e. many exposures). The generator script is
 * committed in the PR description / scratch (`gen_hdr_fixtures.py`). The fixtures
 * are committed + fully offline; this test needs no network and no GPU.
 *
 * This is the FIRST of the two-sided HDR-FLIP verification (spec addendum): here
 * the CPU reference is checked against the official values; the browser harness
 * (`engine/__tests__/hdr-flip.browser.ts`) checks the GPU kernel against this CPU
 * reference.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { flipHDR, computeHdrFlipExposures } from "./hdr-flip-reference.ts";

const here = dirname(fileURLToPath(import.meta.url));
interface Fixture {
  provenance: string;
  ppd: number;
  toneMapper: string;
  cases: {
    name: string;
    width: number;
    height: number;
    refLinRGB: number[];
    testLinRGB: number[];
    expectedFlip: number[];
    expectedMean: number;
  }[];
}
const fx: Fixture = JSON.parse(readFileSync(join(here, "__fixtures__", "flip-hdr.json"), "utf8"));

// The CPU reference is a faithful (not approximate) transcription of the
// official HDR algorithm (exposure range + ACES tone map + per-exposure
// LDR-FLIP + per-pixel max). The small residual vs the compiled .so is float
// precision + the C++/CUDA separated-filter approximation shared with LDR-FLIP.
// Empirically the worst per-pixel residual over these fixtures is ~3.2e-4, so
// 1e-3 is a safe, still-meaningful bound.
const PIXEL_TOL = 1e-3;
const MEAN_TOL = 1e-4;

for (const c of fx.cases) {
  test(`HDR-FLIP CPU reference matches official flip-evaluator: ${c.name}`, () => {
    const got = flipHDR(c.refLinRGB, c.testLinRGB, c.width, c.height, fx.ppd);
    assert.equal(got.length, c.width * c.height, "output length");
    let worst = 0;
    let sum = 0;
    for (let i = 0; i < got.length; i++) {
      const d = Math.abs(got[i]! - c.expectedFlip[i]!);
      if (d > worst) worst = d;
      sum += got[i]!;
    }
    assert.ok(worst <= PIXEL_TOL, `${c.name}: worst per-pixel diff ${worst} > ${PIXEL_TOL}`);
    const mean = sum / got.length;
    assert.ok(
      Math.abs(mean - c.expectedMean) <= MEAN_TOL,
      `${c.name}: mean ${mean} vs official ${c.expectedMean}`,
    );
  });
}

test("HDR-FLIP exposure range is deterministic + widens with dynamic range", () => {
  // The 'wide' fixture (dark bg + bright core) must yield more exposures than
  // the moderate-DR fixtures — the paper's ceil(stop-start) count rule.
  const wide = fx.cases.find((c) => c.name.includes("wide"))!;
  const narrow = fx.cases.find((c) => !c.name.includes("wide"))!;
  const ew = computeHdrFlipExposures(wide.refLinRGB, wide.width, wide.height, 3);
  const en = computeHdrFlipExposures(narrow.refLinRGB, narrow.width, narrow.height, 3);
  assert.ok(ew.numExposures >= 2 && en.numExposures >= 2, "at least 2 exposures");
  assert.ok(ew.numExposures > en.numExposures, `wide (${ew.numExposures}) > narrow (${en.numExposures})`);
  // Deterministic: recompute gives identical values (safe for the params hash).
  const en2 = computeHdrFlipExposures(narrow.refLinRGB, narrow.width, narrow.height, 3);
  assert.deepEqual(en, en2);
});

test("HDR-FLIP honors explicit exposure overrides (skips percentile computation)", () => {
  const c = fx.cases[0]!;
  const overridden = computeHdrFlipExposures(c.refLinRGB, c.width, c.height, 3, {
    startExposure: -2,
    stopExposure: 2,
  });
  assert.equal(overridden.startExposure, -2);
  assert.equal(overridden.stopExposure, 2);
  assert.equal(overridden.numExposures, 4); // max(2, ceil(2 - (-2)))
});

test("HDR-FLIP of identical images is ~0", () => {
  const w = 8;
  const h = 8;
  const img = new Float32Array(w * h * 3);
  for (let i = 0; i < img.length; i++) img[i] = (i % 11) / 3; // some HDR values > 1
  const out = flipHDR(img, img, w, h, 67);
  for (const v of out) assert.ok(v < 1e-6, `identical -> ${v}`);
});
