/**
 * Node test: the CPU SSIM reference (`ssim-reference.ts`) vs scikit-image's
 * `structural_similarity` on committed fixtures.
 *
 * Run:
 *   node --experimental-strip-types --test \
 *     src/lib/cairn-plot/engine/kernels/ssim-reference.test.ts
 *
 * ## Provenance of the expected values (`__fixtures__/ssim.json`)
 * `expectedSsim` (per-pixel map) + `expectedMssim` (interior-crop mean) were
 * generated by scikit-image's `structural_similarity`, invoked on the SAME
 * linear Rec.709 luminance planes this reference computes (sRGB -> linear -> Y,
 * clamped [0,1]) with params `gaussian_weights=True, sigma=1.5,
 * use_sample_covariance=False, data_range=1` (K1=0.01, K2=0.03 defaults). The
 * generator is committed beside the fixture (`gen_ssim_fixtures.py`). Fully
 * offline; needs no network and no GPU.
 *
 * This is the FIRST of the two-sided SSIM verification (spec §diff-kernels):
 * here the CPU reference is checked against skimage; the browser harness
 * (`engine/__tests__/ssim.browser.ts`) checks the GPU kernel against this CPU
 * reference.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ssim } from "./ssim-reference.ts";

const here = dirname(fileURLToPath(import.meta.url));
interface Fixture {
  provenance: string;
  sigma: number;
  K1: number;
  K2: number;
  dataRange: number;
  cases: {
    name: string;
    width: number;
    height: number;
    refSRGB: number[];
    testSRGB: number[];
    expectedSsim: number[];
    expectedMssim: number;
  }[];
}
const fx: Fixture = JSON.parse(readFileSync(join(here, "__fixtures__", "ssim.json"), "utf8"));

// The reference reproduces skimage's separable Gaussian (reflect boundary) in
// f64, so the only residual vs skimage is float rounding + our sRGB->luminance
// front-end vs numpy's. Empirically the worst per-pixel residual over these
// fixtures is ~1e-6, so 1e-4 is a safe, still-meaningful bound.
const PIXEL_TOL = 1e-4;
const MEAN_TOL = 1e-5;

for (const c of fx.cases) {
  test(`SSIM CPU reference matches scikit-image: ${c.name}`, () => {
    const got = ssim(c.refSRGB, c.testSRGB, c.width, c.height);
    assert.equal(got.ssim.length, c.width * c.height, "output length");
    let worst = 0;
    for (let i = 0; i < got.ssim.length; i++) {
      const d = Math.abs(got.ssim[i]! - c.expectedSsim[i]!);
      if (d > worst) worst = d;
    }
    assert.ok(worst <= PIXEL_TOL, `${c.name}: worst per-pixel diff ${worst} > ${PIXEL_TOL}`);
    assert.ok(
      Math.abs(got.mssim - c.expectedMssim) <= MEAN_TOL,
      `${c.name}: mssim ${got.mssim} vs skimage ${c.expectedMssim}`,
    );
  });
}

test("SSIM of identical images is 1 (error 0)", () => {
  // 16x16 so the interior crop (pad=5) is non-empty (6x6) for the mssim check.
  const n = 16 * 16 * 3;
  const img = new Float32Array(n);
  for (let i = 0; i < n; i++) img[i] = (i % 7) / 7;
  const out = ssim(img, img, 16, 16);
  for (const v of out.ssim) assert.ok(Math.abs(v - 1) < 1e-6, `identical -> ${v}`);
  assert.ok(Math.abs(out.mssim - 1) < 1e-6, `identical mssim -> ${out.mssim}`);
});
